/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
	"fmt"
)

// checks if the ConnectorNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorNode{}

// ConnectorNode struct for ConnectorNode
type ConnectorNode struct {
	// A string uniquely identifying this node within the document.
	Id string `json:"id"`
	// The name given to the node by the user in the tool.
	Name string `json:"name"`
	// The type of this node, represented by the string literal \"CONNECTOR\"
	Type string `json:"type"`
	// Whether or not the node is visible on the canvas.
	Visible *bool `json:"visible,omitempty"`
	// If true, layer is locked and cannot be edited
	Locked *bool `json:"locked,omitempty"`
	// Whether the layer is fixed while the parent is scrolling
	// Deprecated
	IsFixed *bool `json:"isFixed,omitempty"`
	// How layer should be treated when the frame is resized
	ScrollBehavior string `json:"scrollBehavior"`
	// The rotation of the node, if not 0.
	Rotation *float32 `json:"rotation,omitempty"`
	// A mapping of a layer's property to component property name of component properties attached to this node. The component property name can be used to look up more information on the corresponding component's or component set's componentPropertyDefinitions.
	ComponentPropertyReferences map[string]string `json:"componentPropertyReferences,omitempty"`
	// Data written by plugins that is visible only to the plugin that wrote it. Requires the `pluginData` to include the ID of the plugin.
	PluginData interface{} `json:"pluginData,omitempty"`
	// Data written by plugins that is visible to all plugins. Requires the `pluginData` parameter to include the string \"shared\".
	SharedPluginData interface{}                 `json:"sharedPluginData,omitempty"`
	BoundVariables   *IsLayerTraitBoundVariables `json:"boundVariables,omitempty"`
	// A mapping of variable collection ID to mode ID representing the explicitly set modes for this node.
	ExplicitVariableModes map[string]string `json:"explicitVariableModes,omitempty"`
	// Bounding box of the node in absolute space coordinates.
	AbsoluteBoundingBox Rectangle `json:"absoluteBoundingBox"`
	// The actual bounds of a node accounting for drop shadows, thick strokes, and anything else that may fall outside the node's regular bounding box defined in `x`, `y`, `width`, and `height`. The `x` and `y` inside this property represent the absolute position of the node on the page. This value will be `null` if the node is invisible.
	AbsoluteRenderBounds Rectangle `json:"absoluteRenderBounds"`
	// Keep height and width constrained to same ratio.
	PreserveRatio *bool `json:"preserveRatio,omitempty"`
	// Horizontal and vertical layout constraints for node.
	Constraints *LayoutConstraint `json:"constraints,omitempty"`
	// The top two rows of a matrix that represents the 2D transform of this node relative to its parent. The bottom row of the matrix is implicitly always (0, 0, 1). Use to transform coordinates in geometry. Only present if `geometry=paths` is passed.
	RelativeTransform [][]float32 `json:"relativeTransform,omitempty"`
	// Width and height of element. This is different from the width and height of the bounding box in that the absolute bounding box represents the element after scaling and rotation. Only present if `geometry=paths` is passed.
	Size *Vector `json:"size,omitempty"`
	//  Determines if the layer should stretch along the parent's counter axis. This property is only provided for direct children of auto-layout frames.  - `INHERIT` - `STRETCH`  In previous versions of auto layout, determined how the layer is aligned inside an auto-layout frame. This property is only provided for direct children of auto-layout frames.  - `MIN` - `CENTER` - `MAX` - `STRETCH`  In horizontal auto-layout frames, \"MIN\" and \"MAX\" correspond to \"TOP\" and \"BOTTOM\". In vertical auto-layout frames, \"MIN\" and \"MAX\" correspond to \"LEFT\" and \"RIGHT\".
	LayoutAlign *string `json:"layoutAlign,omitempty"`
	// This property is applicable only for direct children of auto-layout frames, ignored otherwise. Determines whether a layer should stretch along the parent's primary axis. A `0` corresponds to a fixed size and `1` corresponds to stretch.
	LayoutGrow *float32 `json:"layoutGrow,omitempty"`
	// Determines whether a layer's size and position should be determined by auto-layout settings or manually adjustable.
	LayoutPositioning *string `json:"layoutPositioning,omitempty"`
	// The minimum width of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.
	MinWidth *float32 `json:"minWidth,omitempty"`
	// The maximum width of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.
	MaxWidth *float32 `json:"maxWidth,omitempty"`
	// The minimum height of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.
	MinHeight *float32 `json:"minHeight,omitempty"`
	// The maximum height of the frame. This property is only applicable for auto-layout frames or direct children of auto-layout frames.
	MaxHeight *float32 `json:"maxHeight,omitempty"`
	// The horizontal sizing setting on this auto-layout frame or frame child. - `FIXED` - `HUG`: only valid on auto-layout frames and text nodes - `FILL`: only valid on auto-layout frame children
	LayoutSizingHorizontal *string `json:"layoutSizingHorizontal,omitempty"`
	// The vertical sizing setting on this auto-layout frame or frame child. - `FIXED` - `HUG`: only valid on auto-layout frames and text nodes - `FILL`: only valid on auto-layout frame children
	LayoutSizingVertical *string `json:"layoutSizingVertical,omitempty"`
	// The number of rows in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: \"GRID\"`.
	GridRowCount *float32 `json:"gridRowCount,omitempty"`
	// The number of columns in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: \"GRID\"`.
	GridColumnCount *float32 `json:"gridColumnCount,omitempty"`
	// The distance between rows in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: \"GRID\"`.
	GridRowGap *float32 `json:"gridRowGap,omitempty"`
	// The distance between columns in the grid layout. This property is only applicable for auto-layout frames with `layoutMode: \"GRID\"`.
	GridColumnGap *float32 `json:"gridColumnGap,omitempty"`
	// The string for the CSS grid-template-columns property. This property is only applicable for auto-layout frames with `layoutMode: \"GRID\"`.
	GridColumnsSizing *string `json:"gridColumnsSizing,omitempty"`
	// The string for the CSS grid-template-rows property. This property is only applicable for auto-layout frames with `layoutMode: \"GRID\"`.
	GridRowsSizing *string `json:"gridRowsSizing,omitempty"`
	// Determines how a GRID frame's child should be aligned in the horizontal direction within its grid area. This property is only applicable for direct children of frames with `layoutMode: \"GRID\"`.
	GridChildHorizontalAlign *string `json:"gridChildHorizontalAlign,omitempty"`
	// Determines how a GRID frame's child should be aligned in the vertical direction within its grid area. This property is only applicable for direct children of frames with `layoutMode: \"GRID\"`.
	GridChildVerticalAlign *string `json:"gridChildVerticalAlign,omitempty"`
	// The number of rows that a GRID frame's child should span. This property is only applicable for direct children of frames with `layoutMode: \"GRID\"`.
	GridRowSpan *float32 `json:"gridRowSpan,omitempty"`
	// The number of columns that a GRID frame's child should span. This property is only applicable for direct children of frames with `layoutMode: \"GRID\"`.
	GridColumnSpan *float32 `json:"gridColumnSpan,omitempty"`
	// The index of the row that a GRID frame's child should be anchored to. This property is only applicable for direct children of frames with `layoutMode: \"GRID\"`.
	GridRowAnchorIndex *float32 `json:"gridRowAnchorIndex,omitempty"`
	// The index of the column that a GRID frame's child should be anchored to. This property is only applicable for direct children of frames with `layoutMode: \"GRID\"`.
	GridColumnAnchorIndex *float32 `json:"gridColumnAnchorIndex,omitempty"`
	// How this node blends with nodes behind it in the scene (see blend mode section for more details)
	BlendMode BlendMode `json:"blendMode"`
	// Opacity of the node
	Opacity *float32 `json:"opacity,omitempty"`
	// An array of effects attached to this node (see effects section for more details)
	Effects []Effect `json:"effects"`
	// An array of export settings representing images to export from the node.
	ExportSettings []ExportSetting `json:"exportSettings,omitempty"`
	// Text contained within a text box.
	Characters string `json:"characters"`
	// An array of stroke paints applied to the node.
	Strokes []Paint `json:"strokes,omitempty"`
	// The weight of strokes on the node.
	StrokeWeight *float32 `json:"strokeWeight,omitempty"`
	// Position of stroke relative to vector outline, as a string enum  - `INSIDE`: stroke drawn inside the shape boundary - `OUTSIDE`: stroke drawn outside the shape boundary - `CENTER`: stroke drawn centered along the shape boundary
	StrokeAlign *string `json:"strokeAlign,omitempty"`
	// A string enum with value of \"MITER\", \"BEVEL\", or \"ROUND\", describing how corners in vector paths are rendered.
	StrokeJoin *string `json:"strokeJoin,omitempty"`
	// An array of floating point numbers describing the pattern of dash length and gap lengths that the vector stroke will use when drawn.  For example a value of [1, 2] indicates that the stroke will be drawn with a dash of length 1 followed by a gap of length 2, repeated.
	StrokeDashes []float32 `json:"strokeDashes,omitempty"`
	// The starting point of the connector.
	ConnectorStart ConnectorEndpoint `json:"connectorStart"`
	// The ending point of the connector.
	ConnectorEnd ConnectorEndpoint `json:"connectorEnd"`
	// A string enum describing the end cap of the start of the connector.
	ConnectorStartStrokeCap string `json:"connectorStartStrokeCap"`
	// A string enum describing the end cap of the end of the connector.
	ConnectorEndStrokeCap string `json:"connectorEndStrokeCap"`
	// Connector line type.
	ConnectorLineType ConnectorLineType `json:"connectorLineType"`
	// Connector text background.
	TextBackground       *ConnectorTextBackground `json:"textBackground,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConnectorNode ConnectorNode

// NewConnectorNode instantiates a new ConnectorNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorNode(id string, name string, type_ string, scrollBehavior string, absoluteBoundingBox Rectangle, absoluteRenderBounds Rectangle, blendMode BlendMode, effects []Effect, characters string, connectorStart ConnectorEndpoint, connectorEnd ConnectorEndpoint, connectorStartStrokeCap string, connectorEndStrokeCap string, connectorLineType ConnectorLineType) *ConnectorNode {
	this := ConnectorNode{}
	this.Id = id
	this.Name = name
	this.Type = type_
	var visible bool = true
	this.Visible = &visible
	var locked bool = false
	this.Locked = &locked
	var isFixed bool = false
	this.IsFixed = &isFixed
	this.ScrollBehavior = scrollBehavior
	var rotation float32 = 0
	this.Rotation = &rotation
	this.AbsoluteBoundingBox = absoluteBoundingBox
	this.AbsoluteRenderBounds = absoluteRenderBounds
	var preserveRatio bool = false
	this.PreserveRatio = &preserveRatio
	var layoutGrow float32 = 0
	this.LayoutGrow = &layoutGrow
	var layoutPositioning string = "AUTO"
	this.LayoutPositioning = &layoutPositioning
	var minWidth float32 = 0
	this.MinWidth = &minWidth
	var maxWidth float32 = 0
	this.MaxWidth = &maxWidth
	var minHeight float32 = 0
	this.MinHeight = &minHeight
	var maxHeight float32 = 0
	this.MaxHeight = &maxHeight
	var gridRowGap float32 = 0
	this.GridRowGap = &gridRowGap
	var gridColumnGap float32 = 0
	this.GridColumnGap = &gridColumnGap
	var gridRowSpan float32 = 1
	this.GridRowSpan = &gridRowSpan
	var gridColumnSpan float32 = 1
	this.GridColumnSpan = &gridColumnSpan
	var gridRowAnchorIndex float32 = 0
	this.GridRowAnchorIndex = &gridRowAnchorIndex
	var gridColumnAnchorIndex float32 = 0
	this.GridColumnAnchorIndex = &gridColumnAnchorIndex
	this.BlendMode = blendMode
	var opacity float32 = 1
	this.Opacity = &opacity
	this.Effects = effects
	this.Characters = characters
	var strokeWeight float32 = 1
	this.StrokeWeight = &strokeWeight
	var strokeJoin string = "MITER"
	this.StrokeJoin = &strokeJoin
	this.ConnectorStart = connectorStart
	this.ConnectorEnd = connectorEnd
	this.ConnectorStartStrokeCap = connectorStartStrokeCap
	this.ConnectorEndStrokeCap = connectorEndStrokeCap
	this.ConnectorLineType = connectorLineType
	return &this
}

// NewConnectorNodeWithDefaults instantiates a new ConnectorNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorNodeWithDefaults() *ConnectorNode {
	this := ConnectorNode{}
	var visible bool = true
	this.Visible = &visible
	var locked bool = false
	this.Locked = &locked
	var isFixed bool = false
	this.IsFixed = &isFixed
	var scrollBehavior string = "SCROLLS"
	this.ScrollBehavior = scrollBehavior
	var rotation float32 = 0
	this.Rotation = &rotation
	var preserveRatio bool = false
	this.PreserveRatio = &preserveRatio
	var layoutGrow float32 = 0
	this.LayoutGrow = &layoutGrow
	var layoutPositioning string = "AUTO"
	this.LayoutPositioning = &layoutPositioning
	var minWidth float32 = 0
	this.MinWidth = &minWidth
	var maxWidth float32 = 0
	this.MaxWidth = &maxWidth
	var minHeight float32 = 0
	this.MinHeight = &minHeight
	var maxHeight float32 = 0
	this.MaxHeight = &maxHeight
	var gridRowGap float32 = 0
	this.GridRowGap = &gridRowGap
	var gridColumnGap float32 = 0
	this.GridColumnGap = &gridColumnGap
	var gridRowSpan float32 = 1
	this.GridRowSpan = &gridRowSpan
	var gridColumnSpan float32 = 1
	this.GridColumnSpan = &gridColumnSpan
	var gridRowAnchorIndex float32 = 0
	this.GridRowAnchorIndex = &gridRowAnchorIndex
	var gridColumnAnchorIndex float32 = 0
	this.GridColumnAnchorIndex = &gridColumnAnchorIndex
	var opacity float32 = 1
	this.Opacity = &opacity
	var strokeWeight float32 = 1
	this.StrokeWeight = &strokeWeight
	var strokeJoin string = "MITER"
	this.StrokeJoin = &strokeJoin
	var connectorStartStrokeCap string = "NONE"
	this.ConnectorStartStrokeCap = connectorStartStrokeCap
	var connectorEndStrokeCap string = "NONE"
	this.ConnectorEndStrokeCap = connectorEndStrokeCap
	return &this
}

// GetId returns the Id field value
func (o *ConnectorNode) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConnectorNode) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ConnectorNode) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectorNode) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ConnectorNode) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ConnectorNode) SetType(v string) {
	o.Type = v
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *ConnectorNode) GetVisible() bool {
	if o == nil || IsNil(o.Visible) {
		var ret bool
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetVisibleOk() (*bool, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *ConnectorNode) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given bool and assigns it to the Visible field.
func (o *ConnectorNode) SetVisible(v bool) {
	o.Visible = &v
}

// GetLocked returns the Locked field value if set, zero value otherwise.
func (o *ConnectorNode) GetLocked() bool {
	if o == nil || IsNil(o.Locked) {
		var ret bool
		return ret
	}
	return *o.Locked
}

// GetLockedOk returns a tuple with the Locked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.Locked) {
		return nil, false
	}
	return o.Locked, true
}

// HasLocked returns a boolean if a field has been set.
func (o *ConnectorNode) HasLocked() bool {
	if o != nil && !IsNil(o.Locked) {
		return true
	}

	return false
}

// SetLocked gets a reference to the given bool and assigns it to the Locked field.
func (o *ConnectorNode) SetLocked(v bool) {
	o.Locked = &v
}

// GetIsFixed returns the IsFixed field value if set, zero value otherwise.
// Deprecated
func (o *ConnectorNode) GetIsFixed() bool {
	if o == nil || IsNil(o.IsFixed) {
		var ret bool
		return ret
	}
	return *o.IsFixed
}

// GetIsFixedOk returns a tuple with the IsFixed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ConnectorNode) GetIsFixedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFixed) {
		return nil, false
	}
	return o.IsFixed, true
}

// HasIsFixed returns a boolean if a field has been set.
func (o *ConnectorNode) HasIsFixed() bool {
	if o != nil && !IsNil(o.IsFixed) {
		return true
	}

	return false
}

// SetIsFixed gets a reference to the given bool and assigns it to the IsFixed field.
// Deprecated
func (o *ConnectorNode) SetIsFixed(v bool) {
	o.IsFixed = &v
}

// GetScrollBehavior returns the ScrollBehavior field value
func (o *ConnectorNode) GetScrollBehavior() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScrollBehavior
}

// GetScrollBehaviorOk returns a tuple with the ScrollBehavior field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetScrollBehaviorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScrollBehavior, true
}

// SetScrollBehavior sets field value
func (o *ConnectorNode) SetScrollBehavior(v string) {
	o.ScrollBehavior = v
}

// GetRotation returns the Rotation field value if set, zero value otherwise.
func (o *ConnectorNode) GetRotation() float32 {
	if o == nil || IsNil(o.Rotation) {
		var ret float32
		return ret
	}
	return *o.Rotation
}

// GetRotationOk returns a tuple with the Rotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetRotationOk() (*float32, bool) {
	if o == nil || IsNil(o.Rotation) {
		return nil, false
	}
	return o.Rotation, true
}

// HasRotation returns a boolean if a field has been set.
func (o *ConnectorNode) HasRotation() bool {
	if o != nil && !IsNil(o.Rotation) {
		return true
	}

	return false
}

// SetRotation gets a reference to the given float32 and assigns it to the Rotation field.
func (o *ConnectorNode) SetRotation(v float32) {
	o.Rotation = &v
}

// GetComponentPropertyReferences returns the ComponentPropertyReferences field value if set, zero value otherwise.
func (o *ConnectorNode) GetComponentPropertyReferences() map[string]string {
	if o == nil || IsNil(o.ComponentPropertyReferences) {
		var ret map[string]string
		return ret
	}
	return o.ComponentPropertyReferences
}

// GetComponentPropertyReferencesOk returns a tuple with the ComponentPropertyReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetComponentPropertyReferencesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.ComponentPropertyReferences) {
		return map[string]string{}, false
	}
	return o.ComponentPropertyReferences, true
}

// HasComponentPropertyReferences returns a boolean if a field has been set.
func (o *ConnectorNode) HasComponentPropertyReferences() bool {
	if o != nil && !IsNil(o.ComponentPropertyReferences) {
		return true
	}

	return false
}

// SetComponentPropertyReferences gets a reference to the given map[string]string and assigns it to the ComponentPropertyReferences field.
func (o *ConnectorNode) SetComponentPropertyReferences(v map[string]string) {
	o.ComponentPropertyReferences = v
}

// GetPluginData returns the PluginData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorNode) GetPluginData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PluginData
}

// GetPluginDataOk returns a tuple with the PluginData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorNode) GetPluginDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PluginData) {
		return nil, false
	}
	return &o.PluginData, true
}

// HasPluginData returns a boolean if a field has been set.
func (o *ConnectorNode) HasPluginData() bool {
	if o != nil && !IsNil(o.PluginData) {
		return true
	}

	return false
}

// SetPluginData gets a reference to the given interface{} and assigns it to the PluginData field.
func (o *ConnectorNode) SetPluginData(v interface{}) {
	o.PluginData = v
}

// GetSharedPluginData returns the SharedPluginData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectorNode) GetSharedPluginData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SharedPluginData
}

// GetSharedPluginDataOk returns a tuple with the SharedPluginData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectorNode) GetSharedPluginDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SharedPluginData) {
		return nil, false
	}
	return &o.SharedPluginData, true
}

// HasSharedPluginData returns a boolean if a field has been set.
func (o *ConnectorNode) HasSharedPluginData() bool {
	if o != nil && !IsNil(o.SharedPluginData) {
		return true
	}

	return false
}

// SetSharedPluginData gets a reference to the given interface{} and assigns it to the SharedPluginData field.
func (o *ConnectorNode) SetSharedPluginData(v interface{}) {
	o.SharedPluginData = v
}

// GetBoundVariables returns the BoundVariables field value if set, zero value otherwise.
func (o *ConnectorNode) GetBoundVariables() IsLayerTraitBoundVariables {
	if o == nil || IsNil(o.BoundVariables) {
		var ret IsLayerTraitBoundVariables
		return ret
	}
	return *o.BoundVariables
}

// GetBoundVariablesOk returns a tuple with the BoundVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetBoundVariablesOk() (*IsLayerTraitBoundVariables, bool) {
	if o == nil || IsNil(o.BoundVariables) {
		return nil, false
	}
	return o.BoundVariables, true
}

// HasBoundVariables returns a boolean if a field has been set.
func (o *ConnectorNode) HasBoundVariables() bool {
	if o != nil && !IsNil(o.BoundVariables) {
		return true
	}

	return false
}

// SetBoundVariables gets a reference to the given IsLayerTraitBoundVariables and assigns it to the BoundVariables field.
func (o *ConnectorNode) SetBoundVariables(v IsLayerTraitBoundVariables) {
	o.BoundVariables = &v
}

// GetExplicitVariableModes returns the ExplicitVariableModes field value if set, zero value otherwise.
func (o *ConnectorNode) GetExplicitVariableModes() map[string]string {
	if o == nil || IsNil(o.ExplicitVariableModes) {
		var ret map[string]string
		return ret
	}
	return o.ExplicitVariableModes
}

// GetExplicitVariableModesOk returns a tuple with the ExplicitVariableModes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetExplicitVariableModesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.ExplicitVariableModes) {
		return map[string]string{}, false
	}
	return o.ExplicitVariableModes, true
}

// HasExplicitVariableModes returns a boolean if a field has been set.
func (o *ConnectorNode) HasExplicitVariableModes() bool {
	if o != nil && !IsNil(o.ExplicitVariableModes) {
		return true
	}

	return false
}

// SetExplicitVariableModes gets a reference to the given map[string]string and assigns it to the ExplicitVariableModes field.
func (o *ConnectorNode) SetExplicitVariableModes(v map[string]string) {
	o.ExplicitVariableModes = v
}

// GetAbsoluteBoundingBox returns the AbsoluteBoundingBox field value
func (o *ConnectorNode) GetAbsoluteBoundingBox() Rectangle {
	if o == nil {
		var ret Rectangle
		return ret
	}

	return o.AbsoluteBoundingBox
}

// GetAbsoluteBoundingBoxOk returns a tuple with the AbsoluteBoundingBox field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetAbsoluteBoundingBoxOk() (*Rectangle, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AbsoluteBoundingBox, true
}

// SetAbsoluteBoundingBox sets field value
func (o *ConnectorNode) SetAbsoluteBoundingBox(v Rectangle) {
	o.AbsoluteBoundingBox = v
}

// GetAbsoluteRenderBounds returns the AbsoluteRenderBounds field value
func (o *ConnectorNode) GetAbsoluteRenderBounds() Rectangle {
	if o == nil {
		var ret Rectangle
		return ret
	}

	return o.AbsoluteRenderBounds
}

// GetAbsoluteRenderBoundsOk returns a tuple with the AbsoluteRenderBounds field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetAbsoluteRenderBoundsOk() (*Rectangle, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AbsoluteRenderBounds, true
}

// SetAbsoluteRenderBounds sets field value
func (o *ConnectorNode) SetAbsoluteRenderBounds(v Rectangle) {
	o.AbsoluteRenderBounds = v
}

// GetPreserveRatio returns the PreserveRatio field value if set, zero value otherwise.
func (o *ConnectorNode) GetPreserveRatio() bool {
	if o == nil || IsNil(o.PreserveRatio) {
		var ret bool
		return ret
	}
	return *o.PreserveRatio
}

// GetPreserveRatioOk returns a tuple with the PreserveRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetPreserveRatioOk() (*bool, bool) {
	if o == nil || IsNil(o.PreserveRatio) {
		return nil, false
	}
	return o.PreserveRatio, true
}

// HasPreserveRatio returns a boolean if a field has been set.
func (o *ConnectorNode) HasPreserveRatio() bool {
	if o != nil && !IsNil(o.PreserveRatio) {
		return true
	}

	return false
}

// SetPreserveRatio gets a reference to the given bool and assigns it to the PreserveRatio field.
func (o *ConnectorNode) SetPreserveRatio(v bool) {
	o.PreserveRatio = &v
}

// GetConstraints returns the Constraints field value if set, zero value otherwise.
func (o *ConnectorNode) GetConstraints() LayoutConstraint {
	if o == nil || IsNil(o.Constraints) {
		var ret LayoutConstraint
		return ret
	}
	return *o.Constraints
}

// GetConstraintsOk returns a tuple with the Constraints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetConstraintsOk() (*LayoutConstraint, bool) {
	if o == nil || IsNil(o.Constraints) {
		return nil, false
	}
	return o.Constraints, true
}

// HasConstraints returns a boolean if a field has been set.
func (o *ConnectorNode) HasConstraints() bool {
	if o != nil && !IsNil(o.Constraints) {
		return true
	}

	return false
}

// SetConstraints gets a reference to the given LayoutConstraint and assigns it to the Constraints field.
func (o *ConnectorNode) SetConstraints(v LayoutConstraint) {
	o.Constraints = &v
}

// GetRelativeTransform returns the RelativeTransform field value if set, zero value otherwise.
func (o *ConnectorNode) GetRelativeTransform() [][]float32 {
	if o == nil || IsNil(o.RelativeTransform) {
		var ret [][]float32
		return ret
	}
	return o.RelativeTransform
}

// GetRelativeTransformOk returns a tuple with the RelativeTransform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetRelativeTransformOk() ([][]float32, bool) {
	if o == nil || IsNil(o.RelativeTransform) {
		return nil, false
	}
	return o.RelativeTransform, true
}

// HasRelativeTransform returns a boolean if a field has been set.
func (o *ConnectorNode) HasRelativeTransform() bool {
	if o != nil && !IsNil(o.RelativeTransform) {
		return true
	}

	return false
}

// SetRelativeTransform gets a reference to the given [][]float32 and assigns it to the RelativeTransform field.
func (o *ConnectorNode) SetRelativeTransform(v [][]float32) {
	o.RelativeTransform = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ConnectorNode) GetSize() Vector {
	if o == nil || IsNil(o.Size) {
		var ret Vector
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetSizeOk() (*Vector, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ConnectorNode) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given Vector and assigns it to the Size field.
func (o *ConnectorNode) SetSize(v Vector) {
	o.Size = &v
}

// GetLayoutAlign returns the LayoutAlign field value if set, zero value otherwise.
func (o *ConnectorNode) GetLayoutAlign() string {
	if o == nil || IsNil(o.LayoutAlign) {
		var ret string
		return ret
	}
	return *o.LayoutAlign
}

// GetLayoutAlignOk returns a tuple with the LayoutAlign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetLayoutAlignOk() (*string, bool) {
	if o == nil || IsNil(o.LayoutAlign) {
		return nil, false
	}
	return o.LayoutAlign, true
}

// HasLayoutAlign returns a boolean if a field has been set.
func (o *ConnectorNode) HasLayoutAlign() bool {
	if o != nil && !IsNil(o.LayoutAlign) {
		return true
	}

	return false
}

// SetLayoutAlign gets a reference to the given string and assigns it to the LayoutAlign field.
func (o *ConnectorNode) SetLayoutAlign(v string) {
	o.LayoutAlign = &v
}

// GetLayoutGrow returns the LayoutGrow field value if set, zero value otherwise.
func (o *ConnectorNode) GetLayoutGrow() float32 {
	if o == nil || IsNil(o.LayoutGrow) {
		var ret float32
		return ret
	}
	return *o.LayoutGrow
}

// GetLayoutGrowOk returns a tuple with the LayoutGrow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetLayoutGrowOk() (*float32, bool) {
	if o == nil || IsNil(o.LayoutGrow) {
		return nil, false
	}
	return o.LayoutGrow, true
}

// HasLayoutGrow returns a boolean if a field has been set.
func (o *ConnectorNode) HasLayoutGrow() bool {
	if o != nil && !IsNil(o.LayoutGrow) {
		return true
	}

	return false
}

// SetLayoutGrow gets a reference to the given float32 and assigns it to the LayoutGrow field.
func (o *ConnectorNode) SetLayoutGrow(v float32) {
	o.LayoutGrow = &v
}

// GetLayoutPositioning returns the LayoutPositioning field value if set, zero value otherwise.
func (o *ConnectorNode) GetLayoutPositioning() string {
	if o == nil || IsNil(o.LayoutPositioning) {
		var ret string
		return ret
	}
	return *o.LayoutPositioning
}

// GetLayoutPositioningOk returns a tuple with the LayoutPositioning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetLayoutPositioningOk() (*string, bool) {
	if o == nil || IsNil(o.LayoutPositioning) {
		return nil, false
	}
	return o.LayoutPositioning, true
}

// HasLayoutPositioning returns a boolean if a field has been set.
func (o *ConnectorNode) HasLayoutPositioning() bool {
	if o != nil && !IsNil(o.LayoutPositioning) {
		return true
	}

	return false
}

// SetLayoutPositioning gets a reference to the given string and assigns it to the LayoutPositioning field.
func (o *ConnectorNode) SetLayoutPositioning(v string) {
	o.LayoutPositioning = &v
}

// GetMinWidth returns the MinWidth field value if set, zero value otherwise.
func (o *ConnectorNode) GetMinWidth() float32 {
	if o == nil || IsNil(o.MinWidth) {
		var ret float32
		return ret
	}
	return *o.MinWidth
}

// GetMinWidthOk returns a tuple with the MinWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetMinWidthOk() (*float32, bool) {
	if o == nil || IsNil(o.MinWidth) {
		return nil, false
	}
	return o.MinWidth, true
}

// HasMinWidth returns a boolean if a field has been set.
func (o *ConnectorNode) HasMinWidth() bool {
	if o != nil && !IsNil(o.MinWidth) {
		return true
	}

	return false
}

// SetMinWidth gets a reference to the given float32 and assigns it to the MinWidth field.
func (o *ConnectorNode) SetMinWidth(v float32) {
	o.MinWidth = &v
}

// GetMaxWidth returns the MaxWidth field value if set, zero value otherwise.
func (o *ConnectorNode) GetMaxWidth() float32 {
	if o == nil || IsNil(o.MaxWidth) {
		var ret float32
		return ret
	}
	return *o.MaxWidth
}

// GetMaxWidthOk returns a tuple with the MaxWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetMaxWidthOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxWidth) {
		return nil, false
	}
	return o.MaxWidth, true
}

// HasMaxWidth returns a boolean if a field has been set.
func (o *ConnectorNode) HasMaxWidth() bool {
	if o != nil && !IsNil(o.MaxWidth) {
		return true
	}

	return false
}

// SetMaxWidth gets a reference to the given float32 and assigns it to the MaxWidth field.
func (o *ConnectorNode) SetMaxWidth(v float32) {
	o.MaxWidth = &v
}

// GetMinHeight returns the MinHeight field value if set, zero value otherwise.
func (o *ConnectorNode) GetMinHeight() float32 {
	if o == nil || IsNil(o.MinHeight) {
		var ret float32
		return ret
	}
	return *o.MinHeight
}

// GetMinHeightOk returns a tuple with the MinHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetMinHeightOk() (*float32, bool) {
	if o == nil || IsNil(o.MinHeight) {
		return nil, false
	}
	return o.MinHeight, true
}

// HasMinHeight returns a boolean if a field has been set.
func (o *ConnectorNode) HasMinHeight() bool {
	if o != nil && !IsNil(o.MinHeight) {
		return true
	}

	return false
}

// SetMinHeight gets a reference to the given float32 and assigns it to the MinHeight field.
func (o *ConnectorNode) SetMinHeight(v float32) {
	o.MinHeight = &v
}

// GetMaxHeight returns the MaxHeight field value if set, zero value otherwise.
func (o *ConnectorNode) GetMaxHeight() float32 {
	if o == nil || IsNil(o.MaxHeight) {
		var ret float32
		return ret
	}
	return *o.MaxHeight
}

// GetMaxHeightOk returns a tuple with the MaxHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetMaxHeightOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxHeight) {
		return nil, false
	}
	return o.MaxHeight, true
}

// HasMaxHeight returns a boolean if a field has been set.
func (o *ConnectorNode) HasMaxHeight() bool {
	if o != nil && !IsNil(o.MaxHeight) {
		return true
	}

	return false
}

// SetMaxHeight gets a reference to the given float32 and assigns it to the MaxHeight field.
func (o *ConnectorNode) SetMaxHeight(v float32) {
	o.MaxHeight = &v
}

// GetLayoutSizingHorizontal returns the LayoutSizingHorizontal field value if set, zero value otherwise.
func (o *ConnectorNode) GetLayoutSizingHorizontal() string {
	if o == nil || IsNil(o.LayoutSizingHorizontal) {
		var ret string
		return ret
	}
	return *o.LayoutSizingHorizontal
}

// GetLayoutSizingHorizontalOk returns a tuple with the LayoutSizingHorizontal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetLayoutSizingHorizontalOk() (*string, bool) {
	if o == nil || IsNil(o.LayoutSizingHorizontal) {
		return nil, false
	}
	return o.LayoutSizingHorizontal, true
}

// HasLayoutSizingHorizontal returns a boolean if a field has been set.
func (o *ConnectorNode) HasLayoutSizingHorizontal() bool {
	if o != nil && !IsNil(o.LayoutSizingHorizontal) {
		return true
	}

	return false
}

// SetLayoutSizingHorizontal gets a reference to the given string and assigns it to the LayoutSizingHorizontal field.
func (o *ConnectorNode) SetLayoutSizingHorizontal(v string) {
	o.LayoutSizingHorizontal = &v
}

// GetLayoutSizingVertical returns the LayoutSizingVertical field value if set, zero value otherwise.
func (o *ConnectorNode) GetLayoutSizingVertical() string {
	if o == nil || IsNil(o.LayoutSizingVertical) {
		var ret string
		return ret
	}
	return *o.LayoutSizingVertical
}

// GetLayoutSizingVerticalOk returns a tuple with the LayoutSizingVertical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetLayoutSizingVerticalOk() (*string, bool) {
	if o == nil || IsNil(o.LayoutSizingVertical) {
		return nil, false
	}
	return o.LayoutSizingVertical, true
}

// HasLayoutSizingVertical returns a boolean if a field has been set.
func (o *ConnectorNode) HasLayoutSizingVertical() bool {
	if o != nil && !IsNil(o.LayoutSizingVertical) {
		return true
	}

	return false
}

// SetLayoutSizingVertical gets a reference to the given string and assigns it to the LayoutSizingVertical field.
func (o *ConnectorNode) SetLayoutSizingVertical(v string) {
	o.LayoutSizingVertical = &v
}

// GetGridRowCount returns the GridRowCount field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridRowCount() float32 {
	if o == nil || IsNil(o.GridRowCount) {
		var ret float32
		return ret
	}
	return *o.GridRowCount
}

// GetGridRowCountOk returns a tuple with the GridRowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridRowCountOk() (*float32, bool) {
	if o == nil || IsNil(o.GridRowCount) {
		return nil, false
	}
	return o.GridRowCount, true
}

// HasGridRowCount returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridRowCount() bool {
	if o != nil && !IsNil(o.GridRowCount) {
		return true
	}

	return false
}

// SetGridRowCount gets a reference to the given float32 and assigns it to the GridRowCount field.
func (o *ConnectorNode) SetGridRowCount(v float32) {
	o.GridRowCount = &v
}

// GetGridColumnCount returns the GridColumnCount field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridColumnCount() float32 {
	if o == nil || IsNil(o.GridColumnCount) {
		var ret float32
		return ret
	}
	return *o.GridColumnCount
}

// GetGridColumnCountOk returns a tuple with the GridColumnCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridColumnCountOk() (*float32, bool) {
	if o == nil || IsNil(o.GridColumnCount) {
		return nil, false
	}
	return o.GridColumnCount, true
}

// HasGridColumnCount returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridColumnCount() bool {
	if o != nil && !IsNil(o.GridColumnCount) {
		return true
	}

	return false
}

// SetGridColumnCount gets a reference to the given float32 and assigns it to the GridColumnCount field.
func (o *ConnectorNode) SetGridColumnCount(v float32) {
	o.GridColumnCount = &v
}

// GetGridRowGap returns the GridRowGap field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridRowGap() float32 {
	if o == nil || IsNil(o.GridRowGap) {
		var ret float32
		return ret
	}
	return *o.GridRowGap
}

// GetGridRowGapOk returns a tuple with the GridRowGap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridRowGapOk() (*float32, bool) {
	if o == nil || IsNil(o.GridRowGap) {
		return nil, false
	}
	return o.GridRowGap, true
}

// HasGridRowGap returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridRowGap() bool {
	if o != nil && !IsNil(o.GridRowGap) {
		return true
	}

	return false
}

// SetGridRowGap gets a reference to the given float32 and assigns it to the GridRowGap field.
func (o *ConnectorNode) SetGridRowGap(v float32) {
	o.GridRowGap = &v
}

// GetGridColumnGap returns the GridColumnGap field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridColumnGap() float32 {
	if o == nil || IsNil(o.GridColumnGap) {
		var ret float32
		return ret
	}
	return *o.GridColumnGap
}

// GetGridColumnGapOk returns a tuple with the GridColumnGap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridColumnGapOk() (*float32, bool) {
	if o == nil || IsNil(o.GridColumnGap) {
		return nil, false
	}
	return o.GridColumnGap, true
}

// HasGridColumnGap returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridColumnGap() bool {
	if o != nil && !IsNil(o.GridColumnGap) {
		return true
	}

	return false
}

// SetGridColumnGap gets a reference to the given float32 and assigns it to the GridColumnGap field.
func (o *ConnectorNode) SetGridColumnGap(v float32) {
	o.GridColumnGap = &v
}

// GetGridColumnsSizing returns the GridColumnsSizing field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridColumnsSizing() string {
	if o == nil || IsNil(o.GridColumnsSizing) {
		var ret string
		return ret
	}
	return *o.GridColumnsSizing
}

// GetGridColumnsSizingOk returns a tuple with the GridColumnsSizing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridColumnsSizingOk() (*string, bool) {
	if o == nil || IsNil(o.GridColumnsSizing) {
		return nil, false
	}
	return o.GridColumnsSizing, true
}

// HasGridColumnsSizing returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridColumnsSizing() bool {
	if o != nil && !IsNil(o.GridColumnsSizing) {
		return true
	}

	return false
}

// SetGridColumnsSizing gets a reference to the given string and assigns it to the GridColumnsSizing field.
func (o *ConnectorNode) SetGridColumnsSizing(v string) {
	o.GridColumnsSizing = &v
}

// GetGridRowsSizing returns the GridRowsSizing field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridRowsSizing() string {
	if o == nil || IsNil(o.GridRowsSizing) {
		var ret string
		return ret
	}
	return *o.GridRowsSizing
}

// GetGridRowsSizingOk returns a tuple with the GridRowsSizing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridRowsSizingOk() (*string, bool) {
	if o == nil || IsNil(o.GridRowsSizing) {
		return nil, false
	}
	return o.GridRowsSizing, true
}

// HasGridRowsSizing returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridRowsSizing() bool {
	if o != nil && !IsNil(o.GridRowsSizing) {
		return true
	}

	return false
}

// SetGridRowsSizing gets a reference to the given string and assigns it to the GridRowsSizing field.
func (o *ConnectorNode) SetGridRowsSizing(v string) {
	o.GridRowsSizing = &v
}

// GetGridChildHorizontalAlign returns the GridChildHorizontalAlign field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridChildHorizontalAlign() string {
	if o == nil || IsNil(o.GridChildHorizontalAlign) {
		var ret string
		return ret
	}
	return *o.GridChildHorizontalAlign
}

// GetGridChildHorizontalAlignOk returns a tuple with the GridChildHorizontalAlign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridChildHorizontalAlignOk() (*string, bool) {
	if o == nil || IsNil(o.GridChildHorizontalAlign) {
		return nil, false
	}
	return o.GridChildHorizontalAlign, true
}

// HasGridChildHorizontalAlign returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridChildHorizontalAlign() bool {
	if o != nil && !IsNil(o.GridChildHorizontalAlign) {
		return true
	}

	return false
}

// SetGridChildHorizontalAlign gets a reference to the given string and assigns it to the GridChildHorizontalAlign field.
func (o *ConnectorNode) SetGridChildHorizontalAlign(v string) {
	o.GridChildHorizontalAlign = &v
}

// GetGridChildVerticalAlign returns the GridChildVerticalAlign field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridChildVerticalAlign() string {
	if o == nil || IsNil(o.GridChildVerticalAlign) {
		var ret string
		return ret
	}
	return *o.GridChildVerticalAlign
}

// GetGridChildVerticalAlignOk returns a tuple with the GridChildVerticalAlign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridChildVerticalAlignOk() (*string, bool) {
	if o == nil || IsNil(o.GridChildVerticalAlign) {
		return nil, false
	}
	return o.GridChildVerticalAlign, true
}

// HasGridChildVerticalAlign returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridChildVerticalAlign() bool {
	if o != nil && !IsNil(o.GridChildVerticalAlign) {
		return true
	}

	return false
}

// SetGridChildVerticalAlign gets a reference to the given string and assigns it to the GridChildVerticalAlign field.
func (o *ConnectorNode) SetGridChildVerticalAlign(v string) {
	o.GridChildVerticalAlign = &v
}

// GetGridRowSpan returns the GridRowSpan field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridRowSpan() float32 {
	if o == nil || IsNil(o.GridRowSpan) {
		var ret float32
		return ret
	}
	return *o.GridRowSpan
}

// GetGridRowSpanOk returns a tuple with the GridRowSpan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridRowSpanOk() (*float32, bool) {
	if o == nil || IsNil(o.GridRowSpan) {
		return nil, false
	}
	return o.GridRowSpan, true
}

// HasGridRowSpan returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridRowSpan() bool {
	if o != nil && !IsNil(o.GridRowSpan) {
		return true
	}

	return false
}

// SetGridRowSpan gets a reference to the given float32 and assigns it to the GridRowSpan field.
func (o *ConnectorNode) SetGridRowSpan(v float32) {
	o.GridRowSpan = &v
}

// GetGridColumnSpan returns the GridColumnSpan field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridColumnSpan() float32 {
	if o == nil || IsNil(o.GridColumnSpan) {
		var ret float32
		return ret
	}
	return *o.GridColumnSpan
}

// GetGridColumnSpanOk returns a tuple with the GridColumnSpan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridColumnSpanOk() (*float32, bool) {
	if o == nil || IsNil(o.GridColumnSpan) {
		return nil, false
	}
	return o.GridColumnSpan, true
}

// HasGridColumnSpan returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridColumnSpan() bool {
	if o != nil && !IsNil(o.GridColumnSpan) {
		return true
	}

	return false
}

// SetGridColumnSpan gets a reference to the given float32 and assigns it to the GridColumnSpan field.
func (o *ConnectorNode) SetGridColumnSpan(v float32) {
	o.GridColumnSpan = &v
}

// GetGridRowAnchorIndex returns the GridRowAnchorIndex field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridRowAnchorIndex() float32 {
	if o == nil || IsNil(o.GridRowAnchorIndex) {
		var ret float32
		return ret
	}
	return *o.GridRowAnchorIndex
}

// GetGridRowAnchorIndexOk returns a tuple with the GridRowAnchorIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridRowAnchorIndexOk() (*float32, bool) {
	if o == nil || IsNil(o.GridRowAnchorIndex) {
		return nil, false
	}
	return o.GridRowAnchorIndex, true
}

// HasGridRowAnchorIndex returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridRowAnchorIndex() bool {
	if o != nil && !IsNil(o.GridRowAnchorIndex) {
		return true
	}

	return false
}

// SetGridRowAnchorIndex gets a reference to the given float32 and assigns it to the GridRowAnchorIndex field.
func (o *ConnectorNode) SetGridRowAnchorIndex(v float32) {
	o.GridRowAnchorIndex = &v
}

// GetGridColumnAnchorIndex returns the GridColumnAnchorIndex field value if set, zero value otherwise.
func (o *ConnectorNode) GetGridColumnAnchorIndex() float32 {
	if o == nil || IsNil(o.GridColumnAnchorIndex) {
		var ret float32
		return ret
	}
	return *o.GridColumnAnchorIndex
}

// GetGridColumnAnchorIndexOk returns a tuple with the GridColumnAnchorIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetGridColumnAnchorIndexOk() (*float32, bool) {
	if o == nil || IsNil(o.GridColumnAnchorIndex) {
		return nil, false
	}
	return o.GridColumnAnchorIndex, true
}

// HasGridColumnAnchorIndex returns a boolean if a field has been set.
func (o *ConnectorNode) HasGridColumnAnchorIndex() bool {
	if o != nil && !IsNil(o.GridColumnAnchorIndex) {
		return true
	}

	return false
}

// SetGridColumnAnchorIndex gets a reference to the given float32 and assigns it to the GridColumnAnchorIndex field.
func (o *ConnectorNode) SetGridColumnAnchorIndex(v float32) {
	o.GridColumnAnchorIndex = &v
}

// GetBlendMode returns the BlendMode field value
func (o *ConnectorNode) GetBlendMode() BlendMode {
	if o == nil {
		var ret BlendMode
		return ret
	}

	return o.BlendMode
}

// GetBlendModeOk returns a tuple with the BlendMode field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetBlendModeOk() (*BlendMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlendMode, true
}

// SetBlendMode sets field value
func (o *ConnectorNode) SetBlendMode(v BlendMode) {
	o.BlendMode = v
}

// GetOpacity returns the Opacity field value if set, zero value otherwise.
func (o *ConnectorNode) GetOpacity() float32 {
	if o == nil || IsNil(o.Opacity) {
		var ret float32
		return ret
	}
	return *o.Opacity
}

// GetOpacityOk returns a tuple with the Opacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetOpacityOk() (*float32, bool) {
	if o == nil || IsNil(o.Opacity) {
		return nil, false
	}
	return o.Opacity, true
}

// HasOpacity returns a boolean if a field has been set.
func (o *ConnectorNode) HasOpacity() bool {
	if o != nil && !IsNil(o.Opacity) {
		return true
	}

	return false
}

// SetOpacity gets a reference to the given float32 and assigns it to the Opacity field.
func (o *ConnectorNode) SetOpacity(v float32) {
	o.Opacity = &v
}

// GetEffects returns the Effects field value
func (o *ConnectorNode) GetEffects() []Effect {
	if o == nil {
		var ret []Effect
		return ret
	}

	return o.Effects
}

// GetEffectsOk returns a tuple with the Effects field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetEffectsOk() ([]Effect, bool) {
	if o == nil {
		return nil, false
	}
	return o.Effects, true
}

// SetEffects sets field value
func (o *ConnectorNode) SetEffects(v []Effect) {
	o.Effects = v
}

// GetExportSettings returns the ExportSettings field value if set, zero value otherwise.
func (o *ConnectorNode) GetExportSettings() []ExportSetting {
	if o == nil || IsNil(o.ExportSettings) {
		var ret []ExportSetting
		return ret
	}
	return o.ExportSettings
}

// GetExportSettingsOk returns a tuple with the ExportSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetExportSettingsOk() ([]ExportSetting, bool) {
	if o == nil || IsNil(o.ExportSettings) {
		return nil, false
	}
	return o.ExportSettings, true
}

// HasExportSettings returns a boolean if a field has been set.
func (o *ConnectorNode) HasExportSettings() bool {
	if o != nil && !IsNil(o.ExportSettings) {
		return true
	}

	return false
}

// SetExportSettings gets a reference to the given []ExportSetting and assigns it to the ExportSettings field.
func (o *ConnectorNode) SetExportSettings(v []ExportSetting) {
	o.ExportSettings = v
}

// GetCharacters returns the Characters field value
func (o *ConnectorNode) GetCharacters() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Characters
}

// GetCharactersOk returns a tuple with the Characters field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetCharactersOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Characters, true
}

// SetCharacters sets field value
func (o *ConnectorNode) SetCharacters(v string) {
	o.Characters = v
}

// GetStrokes returns the Strokes field value if set, zero value otherwise.
func (o *ConnectorNode) GetStrokes() []Paint {
	if o == nil || IsNil(o.Strokes) {
		var ret []Paint
		return ret
	}
	return o.Strokes
}

// GetStrokesOk returns a tuple with the Strokes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetStrokesOk() ([]Paint, bool) {
	if o == nil || IsNil(o.Strokes) {
		return nil, false
	}
	return o.Strokes, true
}

// HasStrokes returns a boolean if a field has been set.
func (o *ConnectorNode) HasStrokes() bool {
	if o != nil && !IsNil(o.Strokes) {
		return true
	}

	return false
}

// SetStrokes gets a reference to the given []Paint and assigns it to the Strokes field.
func (o *ConnectorNode) SetStrokes(v []Paint) {
	o.Strokes = v
}

// GetStrokeWeight returns the StrokeWeight field value if set, zero value otherwise.
func (o *ConnectorNode) GetStrokeWeight() float32 {
	if o == nil || IsNil(o.StrokeWeight) {
		var ret float32
		return ret
	}
	return *o.StrokeWeight
}

// GetStrokeWeightOk returns a tuple with the StrokeWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetStrokeWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.StrokeWeight) {
		return nil, false
	}
	return o.StrokeWeight, true
}

// HasStrokeWeight returns a boolean if a field has been set.
func (o *ConnectorNode) HasStrokeWeight() bool {
	if o != nil && !IsNil(o.StrokeWeight) {
		return true
	}

	return false
}

// SetStrokeWeight gets a reference to the given float32 and assigns it to the StrokeWeight field.
func (o *ConnectorNode) SetStrokeWeight(v float32) {
	o.StrokeWeight = &v
}

// GetStrokeAlign returns the StrokeAlign field value if set, zero value otherwise.
func (o *ConnectorNode) GetStrokeAlign() string {
	if o == nil || IsNil(o.StrokeAlign) {
		var ret string
		return ret
	}
	return *o.StrokeAlign
}

// GetStrokeAlignOk returns a tuple with the StrokeAlign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetStrokeAlignOk() (*string, bool) {
	if o == nil || IsNil(o.StrokeAlign) {
		return nil, false
	}
	return o.StrokeAlign, true
}

// HasStrokeAlign returns a boolean if a field has been set.
func (o *ConnectorNode) HasStrokeAlign() bool {
	if o != nil && !IsNil(o.StrokeAlign) {
		return true
	}

	return false
}

// SetStrokeAlign gets a reference to the given string and assigns it to the StrokeAlign field.
func (o *ConnectorNode) SetStrokeAlign(v string) {
	o.StrokeAlign = &v
}

// GetStrokeJoin returns the StrokeJoin field value if set, zero value otherwise.
func (o *ConnectorNode) GetStrokeJoin() string {
	if o == nil || IsNil(o.StrokeJoin) {
		var ret string
		return ret
	}
	return *o.StrokeJoin
}

// GetStrokeJoinOk returns a tuple with the StrokeJoin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetStrokeJoinOk() (*string, bool) {
	if o == nil || IsNil(o.StrokeJoin) {
		return nil, false
	}
	return o.StrokeJoin, true
}

// HasStrokeJoin returns a boolean if a field has been set.
func (o *ConnectorNode) HasStrokeJoin() bool {
	if o != nil && !IsNil(o.StrokeJoin) {
		return true
	}

	return false
}

// SetStrokeJoin gets a reference to the given string and assigns it to the StrokeJoin field.
func (o *ConnectorNode) SetStrokeJoin(v string) {
	o.StrokeJoin = &v
}

// GetStrokeDashes returns the StrokeDashes field value if set, zero value otherwise.
func (o *ConnectorNode) GetStrokeDashes() []float32 {
	if o == nil || IsNil(o.StrokeDashes) {
		var ret []float32
		return ret
	}
	return o.StrokeDashes
}

// GetStrokeDashesOk returns a tuple with the StrokeDashes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetStrokeDashesOk() ([]float32, bool) {
	if o == nil || IsNil(o.StrokeDashes) {
		return nil, false
	}
	return o.StrokeDashes, true
}

// HasStrokeDashes returns a boolean if a field has been set.
func (o *ConnectorNode) HasStrokeDashes() bool {
	if o != nil && !IsNil(o.StrokeDashes) {
		return true
	}

	return false
}

// SetStrokeDashes gets a reference to the given []float32 and assigns it to the StrokeDashes field.
func (o *ConnectorNode) SetStrokeDashes(v []float32) {
	o.StrokeDashes = v
}

// GetConnectorStart returns the ConnectorStart field value
func (o *ConnectorNode) GetConnectorStart() ConnectorEndpoint {
	if o == nil {
		var ret ConnectorEndpoint
		return ret
	}

	return o.ConnectorStart
}

// GetConnectorStartOk returns a tuple with the ConnectorStart field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetConnectorStartOk() (*ConnectorEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorStart, true
}

// SetConnectorStart sets field value
func (o *ConnectorNode) SetConnectorStart(v ConnectorEndpoint) {
	o.ConnectorStart = v
}

// GetConnectorEnd returns the ConnectorEnd field value
func (o *ConnectorNode) GetConnectorEnd() ConnectorEndpoint {
	if o == nil {
		var ret ConnectorEndpoint
		return ret
	}

	return o.ConnectorEnd
}

// GetConnectorEndOk returns a tuple with the ConnectorEnd field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetConnectorEndOk() (*ConnectorEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorEnd, true
}

// SetConnectorEnd sets field value
func (o *ConnectorNode) SetConnectorEnd(v ConnectorEndpoint) {
	o.ConnectorEnd = v
}

// GetConnectorStartStrokeCap returns the ConnectorStartStrokeCap field value
func (o *ConnectorNode) GetConnectorStartStrokeCap() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectorStartStrokeCap
}

// GetConnectorStartStrokeCapOk returns a tuple with the ConnectorStartStrokeCap field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetConnectorStartStrokeCapOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorStartStrokeCap, true
}

// SetConnectorStartStrokeCap sets field value
func (o *ConnectorNode) SetConnectorStartStrokeCap(v string) {
	o.ConnectorStartStrokeCap = v
}

// GetConnectorEndStrokeCap returns the ConnectorEndStrokeCap field value
func (o *ConnectorNode) GetConnectorEndStrokeCap() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectorEndStrokeCap
}

// GetConnectorEndStrokeCapOk returns a tuple with the ConnectorEndStrokeCap field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetConnectorEndStrokeCapOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorEndStrokeCap, true
}

// SetConnectorEndStrokeCap sets field value
func (o *ConnectorNode) SetConnectorEndStrokeCap(v string) {
	o.ConnectorEndStrokeCap = v
}

// GetConnectorLineType returns the ConnectorLineType field value
func (o *ConnectorNode) GetConnectorLineType() ConnectorLineType {
	if o == nil {
		var ret ConnectorLineType
		return ret
	}

	return o.ConnectorLineType
}

// GetConnectorLineTypeOk returns a tuple with the ConnectorLineType field value
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetConnectorLineTypeOk() (*ConnectorLineType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorLineType, true
}

// SetConnectorLineType sets field value
func (o *ConnectorNode) SetConnectorLineType(v ConnectorLineType) {
	o.ConnectorLineType = v
}

// GetTextBackground returns the TextBackground field value if set, zero value otherwise.
func (o *ConnectorNode) GetTextBackground() ConnectorTextBackground {
	if o == nil || IsNil(o.TextBackground) {
		var ret ConnectorTextBackground
		return ret
	}
	return *o.TextBackground
}

// GetTextBackgroundOk returns a tuple with the TextBackground field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorNode) GetTextBackgroundOk() (*ConnectorTextBackground, bool) {
	if o == nil || IsNil(o.TextBackground) {
		return nil, false
	}
	return o.TextBackground, true
}

// HasTextBackground returns a boolean if a field has been set.
func (o *ConnectorNode) HasTextBackground() bool {
	if o != nil && !IsNil(o.TextBackground) {
		return true
	}

	return false
}

// SetTextBackground gets a reference to the given ConnectorTextBackground and assigns it to the TextBackground field.
func (o *ConnectorNode) SetTextBackground(v ConnectorTextBackground) {
	o.TextBackground = &v
}

func (o ConnectorNode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.Locked) {
		toSerialize["locked"] = o.Locked
	}
	if !IsNil(o.IsFixed) {
		toSerialize["isFixed"] = o.IsFixed
	}
	toSerialize["scrollBehavior"] = o.ScrollBehavior
	if !IsNil(o.Rotation) {
		toSerialize["rotation"] = o.Rotation
	}
	if !IsNil(o.ComponentPropertyReferences) {
		toSerialize["componentPropertyReferences"] = o.ComponentPropertyReferences
	}
	if o.PluginData != nil {
		toSerialize["pluginData"] = o.PluginData
	}
	if o.SharedPluginData != nil {
		toSerialize["sharedPluginData"] = o.SharedPluginData
	}
	if !IsNil(o.BoundVariables) {
		toSerialize["boundVariables"] = o.BoundVariables
	}
	if !IsNil(o.ExplicitVariableModes) {
		toSerialize["explicitVariableModes"] = o.ExplicitVariableModes
	}
	toSerialize["absoluteBoundingBox"] = o.AbsoluteBoundingBox
	toSerialize["absoluteRenderBounds"] = o.AbsoluteRenderBounds
	if !IsNil(o.PreserveRatio) {
		toSerialize["preserveRatio"] = o.PreserveRatio
	}
	if !IsNil(o.Constraints) {
		toSerialize["constraints"] = o.Constraints
	}
	if !IsNil(o.RelativeTransform) {
		toSerialize["relativeTransform"] = o.RelativeTransform
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.LayoutAlign) {
		toSerialize["layoutAlign"] = o.LayoutAlign
	}
	if !IsNil(o.LayoutGrow) {
		toSerialize["layoutGrow"] = o.LayoutGrow
	}
	if !IsNil(o.LayoutPositioning) {
		toSerialize["layoutPositioning"] = o.LayoutPositioning
	}
	if !IsNil(o.MinWidth) {
		toSerialize["minWidth"] = o.MinWidth
	}
	if !IsNil(o.MaxWidth) {
		toSerialize["maxWidth"] = o.MaxWidth
	}
	if !IsNil(o.MinHeight) {
		toSerialize["minHeight"] = o.MinHeight
	}
	if !IsNil(o.MaxHeight) {
		toSerialize["maxHeight"] = o.MaxHeight
	}
	if !IsNil(o.LayoutSizingHorizontal) {
		toSerialize["layoutSizingHorizontal"] = o.LayoutSizingHorizontal
	}
	if !IsNil(o.LayoutSizingVertical) {
		toSerialize["layoutSizingVertical"] = o.LayoutSizingVertical
	}
	if !IsNil(o.GridRowCount) {
		toSerialize["gridRowCount"] = o.GridRowCount
	}
	if !IsNil(o.GridColumnCount) {
		toSerialize["gridColumnCount"] = o.GridColumnCount
	}
	if !IsNil(o.GridRowGap) {
		toSerialize["gridRowGap"] = o.GridRowGap
	}
	if !IsNil(o.GridColumnGap) {
		toSerialize["gridColumnGap"] = o.GridColumnGap
	}
	if !IsNil(o.GridColumnsSizing) {
		toSerialize["gridColumnsSizing"] = o.GridColumnsSizing
	}
	if !IsNil(o.GridRowsSizing) {
		toSerialize["gridRowsSizing"] = o.GridRowsSizing
	}
	if !IsNil(o.GridChildHorizontalAlign) {
		toSerialize["gridChildHorizontalAlign"] = o.GridChildHorizontalAlign
	}
	if !IsNil(o.GridChildVerticalAlign) {
		toSerialize["gridChildVerticalAlign"] = o.GridChildVerticalAlign
	}
	if !IsNil(o.GridRowSpan) {
		toSerialize["gridRowSpan"] = o.GridRowSpan
	}
	if !IsNil(o.GridColumnSpan) {
		toSerialize["gridColumnSpan"] = o.GridColumnSpan
	}
	if !IsNil(o.GridRowAnchorIndex) {
		toSerialize["gridRowAnchorIndex"] = o.GridRowAnchorIndex
	}
	if !IsNil(o.GridColumnAnchorIndex) {
		toSerialize["gridColumnAnchorIndex"] = o.GridColumnAnchorIndex
	}
	toSerialize["blendMode"] = o.BlendMode
	if !IsNil(o.Opacity) {
		toSerialize["opacity"] = o.Opacity
	}
	toSerialize["effects"] = o.Effects
	if !IsNil(o.ExportSettings) {
		toSerialize["exportSettings"] = o.ExportSettings
	}
	toSerialize["characters"] = o.Characters
	if !IsNil(o.Strokes) {
		toSerialize["strokes"] = o.Strokes
	}
	if !IsNil(o.StrokeWeight) {
		toSerialize["strokeWeight"] = o.StrokeWeight
	}
	if !IsNil(o.StrokeAlign) {
		toSerialize["strokeAlign"] = o.StrokeAlign
	}
	if !IsNil(o.StrokeJoin) {
		toSerialize["strokeJoin"] = o.StrokeJoin
	}
	if !IsNil(o.StrokeDashes) {
		toSerialize["strokeDashes"] = o.StrokeDashes
	}
	toSerialize["connectorStart"] = o.ConnectorStart
	toSerialize["connectorEnd"] = o.ConnectorEnd
	toSerialize["connectorStartStrokeCap"] = o.ConnectorStartStrokeCap
	toSerialize["connectorEndStrokeCap"] = o.ConnectorEndStrokeCap
	toSerialize["connectorLineType"] = o.ConnectorLineType
	if !IsNil(o.TextBackground) {
		toSerialize["textBackground"] = o.TextBackground
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConnectorNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
		"scrollBehavior",
		"absoluteBoundingBox",
		"absoluteRenderBounds",
		"blendMode",
		"effects",
		"characters",
		"connectorStart",
		"connectorEnd",
		"connectorStartStrokeCap",
		"connectorEndStrokeCap",
		"connectorLineType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorNode := _ConnectorNode{}

	err = json.Unmarshal(data, &varConnectorNode)

	if err != nil {
		return err
	}

	*o = ConnectorNode(varConnectorNode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "visible")
		delete(additionalProperties, "locked")
		delete(additionalProperties, "isFixed")
		delete(additionalProperties, "scrollBehavior")
		delete(additionalProperties, "rotation")
		delete(additionalProperties, "componentPropertyReferences")
		delete(additionalProperties, "pluginData")
		delete(additionalProperties, "sharedPluginData")
		delete(additionalProperties, "boundVariables")
		delete(additionalProperties, "explicitVariableModes")
		delete(additionalProperties, "absoluteBoundingBox")
		delete(additionalProperties, "absoluteRenderBounds")
		delete(additionalProperties, "preserveRatio")
		delete(additionalProperties, "constraints")
		delete(additionalProperties, "relativeTransform")
		delete(additionalProperties, "size")
		delete(additionalProperties, "layoutAlign")
		delete(additionalProperties, "layoutGrow")
		delete(additionalProperties, "layoutPositioning")
		delete(additionalProperties, "minWidth")
		delete(additionalProperties, "maxWidth")
		delete(additionalProperties, "minHeight")
		delete(additionalProperties, "maxHeight")
		delete(additionalProperties, "layoutSizingHorizontal")
		delete(additionalProperties, "layoutSizingVertical")
		delete(additionalProperties, "gridRowCount")
		delete(additionalProperties, "gridColumnCount")
		delete(additionalProperties, "gridRowGap")
		delete(additionalProperties, "gridColumnGap")
		delete(additionalProperties, "gridColumnsSizing")
		delete(additionalProperties, "gridRowsSizing")
		delete(additionalProperties, "gridChildHorizontalAlign")
		delete(additionalProperties, "gridChildVerticalAlign")
		delete(additionalProperties, "gridRowSpan")
		delete(additionalProperties, "gridColumnSpan")
		delete(additionalProperties, "gridRowAnchorIndex")
		delete(additionalProperties, "gridColumnAnchorIndex")
		delete(additionalProperties, "blendMode")
		delete(additionalProperties, "opacity")
		delete(additionalProperties, "effects")
		delete(additionalProperties, "exportSettings")
		delete(additionalProperties, "characters")
		delete(additionalProperties, "strokes")
		delete(additionalProperties, "strokeWeight")
		delete(additionalProperties, "strokeAlign")
		delete(additionalProperties, "strokeJoin")
		delete(additionalProperties, "strokeDashes")
		delete(additionalProperties, "connectorStart")
		delete(additionalProperties, "connectorEnd")
		delete(additionalProperties, "connectorStartStrokeCap")
		delete(additionalProperties, "connectorEndStrokeCap")
		delete(additionalProperties, "connectorLineType")
		delete(additionalProperties, "textBackground")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectorNode struct {
	value *ConnectorNode
	isSet bool
}

func (v NullableConnectorNode) Get() *ConnectorNode {
	return v.value
}

func (v *NullableConnectorNode) Set(val *ConnectorNode) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorNode) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorNode(val *ConnectorNode) *NullableConnectorNode {
	return &NullableConnectorNode{value: val, isSet: true}
}

func (v NullableConnectorNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
