/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
)

// checks if the BaseTypeStyle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseTypeStyle{}

// BaseTypeStyle struct for BaseTypeStyle
type BaseTypeStyle struct {
	// Font family of text (standard name).
	FontFamily *string `json:"fontFamily,omitempty"`
	// PostScript font name.
	FontPostScriptName *string `json:"fontPostScriptName,omitempty"`
	// Describes visual weight or emphasis, such as Bold or Italic.
	FontStyle *string `json:"fontStyle,omitempty"`
	// Whether or not text is italicized.
	Italic *bool `json:"italic,omitempty"`
	// Numeric font weight.
	FontWeight *float32 `json:"fontWeight,omitempty"`
	// Font size in px.
	FontSize *float32 `json:"fontSize,omitempty"`
	// Text casing applied to the node, default is the original casing.
	TextCase *string `json:"textCase,omitempty"`
	// Horizontal text alignment as string enum.
	TextAlignHorizontal *string `json:"textAlignHorizontal,omitempty"`
	// Vertical text alignment as string enum.
	TextAlignVertical *string `json:"textAlignVertical,omitempty"`
	// Space between characters in px.
	LetterSpacing *float32 `json:"letterSpacing,omitempty"`
	// An array of fill paints applied to the characters.
	Fills []Paint `json:"fills,omitempty"`
	// Link to a URL or frame.
	Hyperlink *Hyperlink `json:"hyperlink,omitempty"`
	// A map of OpenType feature flags to 1 or 0, 1 if it is enabled and 0 if it is disabled. Note that some flags aren't reflected here. For example, SMCP (small caps) is still represented by the `textCase` field.
	OpentypeFlags map[string]float32 `json:"opentypeFlags,omitempty"`
	// Indicates how the font weight was overridden when there is a text style override.
	SemanticWeight *string `json:"semanticWeight,omitempty"`
	// Indicates how the font style was overridden when there is a text style override.
	SemanticItalic *string `json:"semanticItalic,omitempty"`
}

// NewBaseTypeStyle instantiates a new BaseTypeStyle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseTypeStyle() *BaseTypeStyle {
	this := BaseTypeStyle{}
	var italic bool = false
	this.Italic = &italic
	return &this
}

// NewBaseTypeStyleWithDefaults instantiates a new BaseTypeStyle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseTypeStyleWithDefaults() *BaseTypeStyle {
	this := BaseTypeStyle{}
	var italic bool = false
	this.Italic = &italic
	return &this
}

// GetFontFamily returns the FontFamily field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetFontFamily() string {
	if o == nil || IsNil(o.FontFamily) {
		var ret string
		return ret
	}
	return *o.FontFamily
}

// GetFontFamilyOk returns a tuple with the FontFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetFontFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.FontFamily) {
		return nil, false
	}
	return o.FontFamily, true
}

// HasFontFamily returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasFontFamily() bool {
	if o != nil && !IsNil(o.FontFamily) {
		return true
	}

	return false
}

// SetFontFamily gets a reference to the given string and assigns it to the FontFamily field.
func (o *BaseTypeStyle) SetFontFamily(v string) {
	o.FontFamily = &v
}

// GetFontPostScriptName returns the FontPostScriptName field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetFontPostScriptName() string {
	if o == nil || IsNil(o.FontPostScriptName) {
		var ret string
		return ret
	}
	return *o.FontPostScriptName
}

// GetFontPostScriptNameOk returns a tuple with the FontPostScriptName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetFontPostScriptNameOk() (*string, bool) {
	if o == nil || IsNil(o.FontPostScriptName) {
		return nil, false
	}
	return o.FontPostScriptName, true
}

// HasFontPostScriptName returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasFontPostScriptName() bool {
	if o != nil && !IsNil(o.FontPostScriptName) {
		return true
	}

	return false
}

// SetFontPostScriptName gets a reference to the given string and assigns it to the FontPostScriptName field.
func (o *BaseTypeStyle) SetFontPostScriptName(v string) {
	o.FontPostScriptName = &v
}

// GetFontStyle returns the FontStyle field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetFontStyle() string {
	if o == nil || IsNil(o.FontStyle) {
		var ret string
		return ret
	}
	return *o.FontStyle
}

// GetFontStyleOk returns a tuple with the FontStyle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetFontStyleOk() (*string, bool) {
	if o == nil || IsNil(o.FontStyle) {
		return nil, false
	}
	return o.FontStyle, true
}

// HasFontStyle returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasFontStyle() bool {
	if o != nil && !IsNil(o.FontStyle) {
		return true
	}

	return false
}

// SetFontStyle gets a reference to the given string and assigns it to the FontStyle field.
func (o *BaseTypeStyle) SetFontStyle(v string) {
	o.FontStyle = &v
}

// GetItalic returns the Italic field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetItalic() bool {
	if o == nil || IsNil(o.Italic) {
		var ret bool
		return ret
	}
	return *o.Italic
}

// GetItalicOk returns a tuple with the Italic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetItalicOk() (*bool, bool) {
	if o == nil || IsNil(o.Italic) {
		return nil, false
	}
	return o.Italic, true
}

// HasItalic returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasItalic() bool {
	if o != nil && !IsNil(o.Italic) {
		return true
	}

	return false
}

// SetItalic gets a reference to the given bool and assigns it to the Italic field.
func (o *BaseTypeStyle) SetItalic(v bool) {
	o.Italic = &v
}

// GetFontWeight returns the FontWeight field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetFontWeight() float32 {
	if o == nil || IsNil(o.FontWeight) {
		var ret float32
		return ret
	}
	return *o.FontWeight
}

// GetFontWeightOk returns a tuple with the FontWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetFontWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.FontWeight) {
		return nil, false
	}
	return o.FontWeight, true
}

// HasFontWeight returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasFontWeight() bool {
	if o != nil && !IsNil(o.FontWeight) {
		return true
	}

	return false
}

// SetFontWeight gets a reference to the given float32 and assigns it to the FontWeight field.
func (o *BaseTypeStyle) SetFontWeight(v float32) {
	o.FontWeight = &v
}

// GetFontSize returns the FontSize field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetFontSize() float32 {
	if o == nil || IsNil(o.FontSize) {
		var ret float32
		return ret
	}
	return *o.FontSize
}

// GetFontSizeOk returns a tuple with the FontSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetFontSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.FontSize) {
		return nil, false
	}
	return o.FontSize, true
}

// HasFontSize returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasFontSize() bool {
	if o != nil && !IsNil(o.FontSize) {
		return true
	}

	return false
}

// SetFontSize gets a reference to the given float32 and assigns it to the FontSize field.
func (o *BaseTypeStyle) SetFontSize(v float32) {
	o.FontSize = &v
}

// GetTextCase returns the TextCase field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetTextCase() string {
	if o == nil || IsNil(o.TextCase) {
		var ret string
		return ret
	}
	return *o.TextCase
}

// GetTextCaseOk returns a tuple with the TextCase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetTextCaseOk() (*string, bool) {
	if o == nil || IsNil(o.TextCase) {
		return nil, false
	}
	return o.TextCase, true
}

// HasTextCase returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasTextCase() bool {
	if o != nil && !IsNil(o.TextCase) {
		return true
	}

	return false
}

// SetTextCase gets a reference to the given string and assigns it to the TextCase field.
func (o *BaseTypeStyle) SetTextCase(v string) {
	o.TextCase = &v
}

// GetTextAlignHorizontal returns the TextAlignHorizontal field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetTextAlignHorizontal() string {
	if o == nil || IsNil(o.TextAlignHorizontal) {
		var ret string
		return ret
	}
	return *o.TextAlignHorizontal
}

// GetTextAlignHorizontalOk returns a tuple with the TextAlignHorizontal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetTextAlignHorizontalOk() (*string, bool) {
	if o == nil || IsNil(o.TextAlignHorizontal) {
		return nil, false
	}
	return o.TextAlignHorizontal, true
}

// HasTextAlignHorizontal returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasTextAlignHorizontal() bool {
	if o != nil && !IsNil(o.TextAlignHorizontal) {
		return true
	}

	return false
}

// SetTextAlignHorizontal gets a reference to the given string and assigns it to the TextAlignHorizontal field.
func (o *BaseTypeStyle) SetTextAlignHorizontal(v string) {
	o.TextAlignHorizontal = &v
}

// GetTextAlignVertical returns the TextAlignVertical field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetTextAlignVertical() string {
	if o == nil || IsNil(o.TextAlignVertical) {
		var ret string
		return ret
	}
	return *o.TextAlignVertical
}

// GetTextAlignVerticalOk returns a tuple with the TextAlignVertical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetTextAlignVerticalOk() (*string, bool) {
	if o == nil || IsNil(o.TextAlignVertical) {
		return nil, false
	}
	return o.TextAlignVertical, true
}

// HasTextAlignVertical returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasTextAlignVertical() bool {
	if o != nil && !IsNil(o.TextAlignVertical) {
		return true
	}

	return false
}

// SetTextAlignVertical gets a reference to the given string and assigns it to the TextAlignVertical field.
func (o *BaseTypeStyle) SetTextAlignVertical(v string) {
	o.TextAlignVertical = &v
}

// GetLetterSpacing returns the LetterSpacing field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetLetterSpacing() float32 {
	if o == nil || IsNil(o.LetterSpacing) {
		var ret float32
		return ret
	}
	return *o.LetterSpacing
}

// GetLetterSpacingOk returns a tuple with the LetterSpacing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetLetterSpacingOk() (*float32, bool) {
	if o == nil || IsNil(o.LetterSpacing) {
		return nil, false
	}
	return o.LetterSpacing, true
}

// HasLetterSpacing returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasLetterSpacing() bool {
	if o != nil && !IsNil(o.LetterSpacing) {
		return true
	}

	return false
}

// SetLetterSpacing gets a reference to the given float32 and assigns it to the LetterSpacing field.
func (o *BaseTypeStyle) SetLetterSpacing(v float32) {
	o.LetterSpacing = &v
}

// GetFills returns the Fills field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetFills() []Paint {
	if o == nil || IsNil(o.Fills) {
		var ret []Paint
		return ret
	}
	return o.Fills
}

// GetFillsOk returns a tuple with the Fills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetFillsOk() ([]Paint, bool) {
	if o == nil || IsNil(o.Fills) {
		return nil, false
	}
	return o.Fills, true
}

// HasFills returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasFills() bool {
	if o != nil && !IsNil(o.Fills) {
		return true
	}

	return false
}

// SetFills gets a reference to the given []Paint and assigns it to the Fills field.
func (o *BaseTypeStyle) SetFills(v []Paint) {
	o.Fills = v
}

// GetHyperlink returns the Hyperlink field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetHyperlink() Hyperlink {
	if o == nil || IsNil(o.Hyperlink) {
		var ret Hyperlink
		return ret
	}
	return *o.Hyperlink
}

// GetHyperlinkOk returns a tuple with the Hyperlink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetHyperlinkOk() (*Hyperlink, bool) {
	if o == nil || IsNil(o.Hyperlink) {
		return nil, false
	}
	return o.Hyperlink, true
}

// HasHyperlink returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasHyperlink() bool {
	if o != nil && !IsNil(o.Hyperlink) {
		return true
	}

	return false
}

// SetHyperlink gets a reference to the given Hyperlink and assigns it to the Hyperlink field.
func (o *BaseTypeStyle) SetHyperlink(v Hyperlink) {
	o.Hyperlink = &v
}

// GetOpentypeFlags returns the OpentypeFlags field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetOpentypeFlags() map[string]float32 {
	if o == nil || IsNil(o.OpentypeFlags) {
		var ret map[string]float32
		return ret
	}
	return o.OpentypeFlags
}

// GetOpentypeFlagsOk returns a tuple with the OpentypeFlags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetOpentypeFlagsOk() (map[string]float32, bool) {
	if o == nil || IsNil(o.OpentypeFlags) {
		return map[string]float32{}, false
	}
	return o.OpentypeFlags, true
}

// HasOpentypeFlags returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasOpentypeFlags() bool {
	if o != nil && !IsNil(o.OpentypeFlags) {
		return true
	}

	return false
}

// SetOpentypeFlags gets a reference to the given map[string]float32 and assigns it to the OpentypeFlags field.
func (o *BaseTypeStyle) SetOpentypeFlags(v map[string]float32) {
	o.OpentypeFlags = v
}

// GetSemanticWeight returns the SemanticWeight field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetSemanticWeight() string {
	if o == nil || IsNil(o.SemanticWeight) {
		var ret string
		return ret
	}
	return *o.SemanticWeight
}

// GetSemanticWeightOk returns a tuple with the SemanticWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetSemanticWeightOk() (*string, bool) {
	if o == nil || IsNil(o.SemanticWeight) {
		return nil, false
	}
	return o.SemanticWeight, true
}

// HasSemanticWeight returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasSemanticWeight() bool {
	if o != nil && !IsNil(o.SemanticWeight) {
		return true
	}

	return false
}

// SetSemanticWeight gets a reference to the given string and assigns it to the SemanticWeight field.
func (o *BaseTypeStyle) SetSemanticWeight(v string) {
	o.SemanticWeight = &v
}

// GetSemanticItalic returns the SemanticItalic field value if set, zero value otherwise.
func (o *BaseTypeStyle) GetSemanticItalic() string {
	if o == nil || IsNil(o.SemanticItalic) {
		var ret string
		return ret
	}
	return *o.SemanticItalic
}

// GetSemanticItalicOk returns a tuple with the SemanticItalic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseTypeStyle) GetSemanticItalicOk() (*string, bool) {
	if o == nil || IsNil(o.SemanticItalic) {
		return nil, false
	}
	return o.SemanticItalic, true
}

// HasSemanticItalic returns a boolean if a field has been set.
func (o *BaseTypeStyle) HasSemanticItalic() bool {
	if o != nil && !IsNil(o.SemanticItalic) {
		return true
	}

	return false
}

// SetSemanticItalic gets a reference to the given string and assigns it to the SemanticItalic field.
func (o *BaseTypeStyle) SetSemanticItalic(v string) {
	o.SemanticItalic = &v
}

func (o BaseTypeStyle) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseTypeStyle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FontFamily) {
		toSerialize["fontFamily"] = o.FontFamily
	}
	if !IsNil(o.FontPostScriptName) {
		toSerialize["fontPostScriptName"] = o.FontPostScriptName
	}
	if !IsNil(o.FontStyle) {
		toSerialize["fontStyle"] = o.FontStyle
	}
	if !IsNil(o.Italic) {
		toSerialize["italic"] = o.Italic
	}
	if !IsNil(o.FontWeight) {
		toSerialize["fontWeight"] = o.FontWeight
	}
	if !IsNil(o.FontSize) {
		toSerialize["fontSize"] = o.FontSize
	}
	if !IsNil(o.TextCase) {
		toSerialize["textCase"] = o.TextCase
	}
	if !IsNil(o.TextAlignHorizontal) {
		toSerialize["textAlignHorizontal"] = o.TextAlignHorizontal
	}
	if !IsNil(o.TextAlignVertical) {
		toSerialize["textAlignVertical"] = o.TextAlignVertical
	}
	if !IsNil(o.LetterSpacing) {
		toSerialize["letterSpacing"] = o.LetterSpacing
	}
	if !IsNil(o.Fills) {
		toSerialize["fills"] = o.Fills
	}
	if !IsNil(o.Hyperlink) {
		toSerialize["hyperlink"] = o.Hyperlink
	}
	if !IsNil(o.OpentypeFlags) {
		toSerialize["opentypeFlags"] = o.OpentypeFlags
	}
	if !IsNil(o.SemanticWeight) {
		toSerialize["semanticWeight"] = o.SemanticWeight
	}
	if !IsNil(o.SemanticItalic) {
		toSerialize["semanticItalic"] = o.SemanticItalic
	}
	return toSerialize, nil
}

type NullableBaseTypeStyle struct {
	value *BaseTypeStyle
	isSet bool
}

func (v NullableBaseTypeStyle) Get() *BaseTypeStyle {
	return v.value
}

func (v *NullableBaseTypeStyle) Set(val *BaseTypeStyle) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseTypeStyle) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseTypeStyle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseTypeStyle(val *BaseTypeStyle) *NullableBaseTypeStyle {
	return &NullableBaseTypeStyle{value: val, isSet: true}
}

func (v NullableBaseTypeStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseTypeStyle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
