/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
	"fmt"
)

// checks if the InstanceSwapPreferredValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceSwapPreferredValue{}

// InstanceSwapPreferredValue Instance swap preferred value.
type InstanceSwapPreferredValue struct {
	// Type of node for this preferred value.
	Type string `json:"type"`
	// Key of this component or component set.
	Key                  string `json:"key"`
	AdditionalProperties map[string]interface{}
}

type _InstanceSwapPreferredValue InstanceSwapPreferredValue

// NewInstanceSwapPreferredValue instantiates a new InstanceSwapPreferredValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceSwapPreferredValue(type_ string, key string) *InstanceSwapPreferredValue {
	this := InstanceSwapPreferredValue{}
	this.Type = type_
	this.Key = key
	return &this
}

// NewInstanceSwapPreferredValueWithDefaults instantiates a new InstanceSwapPreferredValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceSwapPreferredValueWithDefaults() *InstanceSwapPreferredValue {
	this := InstanceSwapPreferredValue{}
	return &this
}

// GetType returns the Type field value
func (o *InstanceSwapPreferredValue) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InstanceSwapPreferredValue) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InstanceSwapPreferredValue) SetType(v string) {
	o.Type = v
}

// GetKey returns the Key field value
func (o *InstanceSwapPreferredValue) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *InstanceSwapPreferredValue) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *InstanceSwapPreferredValue) SetKey(v string) {
	o.Key = v
}

func (o InstanceSwapPreferredValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceSwapPreferredValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["key"] = o.Key

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InstanceSwapPreferredValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceSwapPreferredValue := _InstanceSwapPreferredValue{}

	err = json.Unmarshal(data, &varInstanceSwapPreferredValue)

	if err != nil {
		return err
	}

	*o = InstanceSwapPreferredValue(varInstanceSwapPreferredValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInstanceSwapPreferredValue struct {
	value *InstanceSwapPreferredValue
	isSet bool
}

func (v NullableInstanceSwapPreferredValue) Get() *InstanceSwapPreferredValue {
	return v.value
}

func (v *NullableInstanceSwapPreferredValue) Set(val *InstanceSwapPreferredValue) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceSwapPreferredValue) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceSwapPreferredValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceSwapPreferredValue(val *InstanceSwapPreferredValue) *NullableInstanceSwapPreferredValue {
	return &NullableInstanceSwapPreferredValue{value: val, isSet: true}
}

func (v NullableInstanceSwapPreferredValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceSwapPreferredValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
