/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
)

// checks if the IndividualStrokesTrait type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndividualStrokesTrait{}

// IndividualStrokesTrait struct for IndividualStrokesTrait
type IndividualStrokesTrait struct {
	// An object including the top, bottom, left, and right stroke weights. Only returned if individual stroke weights are used.
	IndividualStrokeWeights *StrokeWeights `json:"individualStrokeWeights,omitempty"`
	AdditionalProperties    map[string]interface{}
}

type _IndividualStrokesTrait IndividualStrokesTrait

// NewIndividualStrokesTrait instantiates a new IndividualStrokesTrait object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndividualStrokesTrait() *IndividualStrokesTrait {
	this := IndividualStrokesTrait{}
	return &this
}

// NewIndividualStrokesTraitWithDefaults instantiates a new IndividualStrokesTrait object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndividualStrokesTraitWithDefaults() *IndividualStrokesTrait {
	this := IndividualStrokesTrait{}
	return &this
}

// GetIndividualStrokeWeights returns the IndividualStrokeWeights field value if set, zero value otherwise.
func (o *IndividualStrokesTrait) GetIndividualStrokeWeights() StrokeWeights {
	if o == nil || IsNil(o.IndividualStrokeWeights) {
		var ret StrokeWeights
		return ret
	}
	return *o.IndividualStrokeWeights
}

// GetIndividualStrokeWeightsOk returns a tuple with the IndividualStrokeWeights field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualStrokesTrait) GetIndividualStrokeWeightsOk() (*StrokeWeights, bool) {
	if o == nil || IsNil(o.IndividualStrokeWeights) {
		return nil, false
	}
	return o.IndividualStrokeWeights, true
}

// HasIndividualStrokeWeights returns a boolean if a field has been set.
func (o *IndividualStrokesTrait) HasIndividualStrokeWeights() bool {
	if o != nil && !IsNil(o.IndividualStrokeWeights) {
		return true
	}

	return false
}

// SetIndividualStrokeWeights gets a reference to the given StrokeWeights and assigns it to the IndividualStrokeWeights field.
func (o *IndividualStrokesTrait) SetIndividualStrokeWeights(v StrokeWeights) {
	o.IndividualStrokeWeights = &v
}

func (o IndividualStrokesTrait) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndividualStrokesTrait) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IndividualStrokeWeights) {
		toSerialize["individualStrokeWeights"] = o.IndividualStrokeWeights
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IndividualStrokesTrait) UnmarshalJSON(data []byte) (err error) {
	varIndividualStrokesTrait := _IndividualStrokesTrait{}

	err = json.Unmarshal(data, &varIndividualStrokesTrait)

	if err != nil {
		return err
	}

	*o = IndividualStrokesTrait(varIndividualStrokesTrait)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "individualStrokeWeights")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIndividualStrokesTrait struct {
	value *IndividualStrokesTrait
	isSet bool
}

func (v NullableIndividualStrokesTrait) Get() *IndividualStrokesTrait {
	return v.value
}

func (v *NullableIndividualStrokesTrait) Set(val *IndividualStrokesTrait) {
	v.value = val
	v.isSet = true
}

func (v NullableIndividualStrokesTrait) IsSet() bool {
	return v.isSet
}

func (v *NullableIndividualStrokesTrait) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndividualStrokesTrait(val *IndividualStrokesTrait) *NullableIndividualStrokesTrait {
	return &NullableIndividualStrokesTrait{value: val, isSet: true}
}

func (v NullableIndividualStrokesTrait) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndividualStrokesTrait) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
