/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Vector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vector{}

// Vector A 2d vector.
type Vector struct {
	// X coordinate of the vector.
	X float32 `json:"x"`
	// Y coordinate of the vector.
	Y float32 `json:"y"`
}

type _Vector Vector

// NewVector instantiates a new Vector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVector(x float32, y float32) *Vector {
	this := Vector{}
	this.X = x
	this.Y = y
	return &this
}

// NewVectorWithDefaults instantiates a new Vector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorWithDefaults() *Vector {
	this := Vector{}
	return &this
}

// GetX returns the X field value
func (o *Vector) GetX() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *Vector) GetXOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *Vector) SetX(v float32) {
	o.X = v
}

// GetY returns the Y field value
func (o *Vector) GetY() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *Vector) GetYOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *Vector) SetY(v float32) {
	o.Y = v
}

func (o Vector) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	return toSerialize, nil
}

func (o *Vector) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x",
		"y",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVector := _Vector{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVector)

	if err != nil {
		return err
	}

	*o = Vector(varVector)

	return err
}

type NullableVector struct {
	value *Vector
	isSet bool
}

func (v NullableVector) Get() *Vector {
	return v.value
}

func (v *NullableVector) Set(val *Vector) {
	v.value = val
	v.isSet = true
}

func (v NullableVector) IsSet() bool {
	return v.isSet
}

func (v *NullableVector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVector(val *Vector) *NullableVector {
	return &NullableVector{value: val, isSet: true}
}

func (v NullableVector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
