/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
)

// checks if the MinimalStrokesTrait type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MinimalStrokesTrait{}

// MinimalStrokesTrait struct for MinimalStrokesTrait
type MinimalStrokesTrait struct {
	// An array of stroke paints applied to the node.
	Strokes []Paint `json:"strokes,omitempty"`
	// The weight of strokes on the node.
	StrokeWeight *float32 `json:"strokeWeight,omitempty"`
	// Position of stroke relative to vector outline, as a string enum  - `INSIDE`: stroke drawn inside the shape boundary - `OUTSIDE`: stroke drawn outside the shape boundary - `CENTER`: stroke drawn centered along the shape boundary
	StrokeAlign *string `json:"strokeAlign,omitempty"`
	// A string enum with value of \"MITER\", \"BEVEL\", or \"ROUND\", describing how corners in vector paths are rendered.
	StrokeJoin *string `json:"strokeJoin,omitempty"`
	// An array of floating point numbers describing the pattern of dash length and gap lengths that the vector stroke will use when drawn.  For example a value of [1, 2] indicates that the stroke will be drawn with a dash of length 1 followed by a gap of length 2, repeated.
	StrokeDashes         []float32 `json:"strokeDashes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MinimalStrokesTrait MinimalStrokesTrait

// NewMinimalStrokesTrait instantiates a new MinimalStrokesTrait object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMinimalStrokesTrait() *MinimalStrokesTrait {
	this := MinimalStrokesTrait{}
	var strokeWeight float32 = 1
	this.StrokeWeight = &strokeWeight
	var strokeJoin string = "MITER"
	this.StrokeJoin = &strokeJoin
	return &this
}

// NewMinimalStrokesTraitWithDefaults instantiates a new MinimalStrokesTrait object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMinimalStrokesTraitWithDefaults() *MinimalStrokesTrait {
	this := MinimalStrokesTrait{}
	var strokeWeight float32 = 1
	this.StrokeWeight = &strokeWeight
	var strokeJoin string = "MITER"
	this.StrokeJoin = &strokeJoin
	return &this
}

// GetStrokes returns the Strokes field value if set, zero value otherwise.
func (o *MinimalStrokesTrait) GetStrokes() []Paint {
	if o == nil || IsNil(o.Strokes) {
		var ret []Paint
		return ret
	}
	return o.Strokes
}

// GetStrokesOk returns a tuple with the Strokes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalStrokesTrait) GetStrokesOk() ([]Paint, bool) {
	if o == nil || IsNil(o.Strokes) {
		return nil, false
	}
	return o.Strokes, true
}

// HasStrokes returns a boolean if a field has been set.
func (o *MinimalStrokesTrait) HasStrokes() bool {
	if o != nil && !IsNil(o.Strokes) {
		return true
	}

	return false
}

// SetStrokes gets a reference to the given []Paint and assigns it to the Strokes field.
func (o *MinimalStrokesTrait) SetStrokes(v []Paint) {
	o.Strokes = v
}

// GetStrokeWeight returns the StrokeWeight field value if set, zero value otherwise.
func (o *MinimalStrokesTrait) GetStrokeWeight() float32 {
	if o == nil || IsNil(o.StrokeWeight) {
		var ret float32
		return ret
	}
	return *o.StrokeWeight
}

// GetStrokeWeightOk returns a tuple with the StrokeWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalStrokesTrait) GetStrokeWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.StrokeWeight) {
		return nil, false
	}
	return o.StrokeWeight, true
}

// HasStrokeWeight returns a boolean if a field has been set.
func (o *MinimalStrokesTrait) HasStrokeWeight() bool {
	if o != nil && !IsNil(o.StrokeWeight) {
		return true
	}

	return false
}

// SetStrokeWeight gets a reference to the given float32 and assigns it to the StrokeWeight field.
func (o *MinimalStrokesTrait) SetStrokeWeight(v float32) {
	o.StrokeWeight = &v
}

// GetStrokeAlign returns the StrokeAlign field value if set, zero value otherwise.
func (o *MinimalStrokesTrait) GetStrokeAlign() string {
	if o == nil || IsNil(o.StrokeAlign) {
		var ret string
		return ret
	}
	return *o.StrokeAlign
}

// GetStrokeAlignOk returns a tuple with the StrokeAlign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalStrokesTrait) GetStrokeAlignOk() (*string, bool) {
	if o == nil || IsNil(o.StrokeAlign) {
		return nil, false
	}
	return o.StrokeAlign, true
}

// HasStrokeAlign returns a boolean if a field has been set.
func (o *MinimalStrokesTrait) HasStrokeAlign() bool {
	if o != nil && !IsNil(o.StrokeAlign) {
		return true
	}

	return false
}

// SetStrokeAlign gets a reference to the given string and assigns it to the StrokeAlign field.
func (o *MinimalStrokesTrait) SetStrokeAlign(v string) {
	o.StrokeAlign = &v
}

// GetStrokeJoin returns the StrokeJoin field value if set, zero value otherwise.
func (o *MinimalStrokesTrait) GetStrokeJoin() string {
	if o == nil || IsNil(o.StrokeJoin) {
		var ret string
		return ret
	}
	return *o.StrokeJoin
}

// GetStrokeJoinOk returns a tuple with the StrokeJoin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalStrokesTrait) GetStrokeJoinOk() (*string, bool) {
	if o == nil || IsNil(o.StrokeJoin) {
		return nil, false
	}
	return o.StrokeJoin, true
}

// HasStrokeJoin returns a boolean if a field has been set.
func (o *MinimalStrokesTrait) HasStrokeJoin() bool {
	if o != nil && !IsNil(o.StrokeJoin) {
		return true
	}

	return false
}

// SetStrokeJoin gets a reference to the given string and assigns it to the StrokeJoin field.
func (o *MinimalStrokesTrait) SetStrokeJoin(v string) {
	o.StrokeJoin = &v
}

// GetStrokeDashes returns the StrokeDashes field value if set, zero value otherwise.
func (o *MinimalStrokesTrait) GetStrokeDashes() []float32 {
	if o == nil || IsNil(o.StrokeDashes) {
		var ret []float32
		return ret
	}
	return o.StrokeDashes
}

// GetStrokeDashesOk returns a tuple with the StrokeDashes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MinimalStrokesTrait) GetStrokeDashesOk() ([]float32, bool) {
	if o == nil || IsNil(o.StrokeDashes) {
		return nil, false
	}
	return o.StrokeDashes, true
}

// HasStrokeDashes returns a boolean if a field has been set.
func (o *MinimalStrokesTrait) HasStrokeDashes() bool {
	if o != nil && !IsNil(o.StrokeDashes) {
		return true
	}

	return false
}

// SetStrokeDashes gets a reference to the given []float32 and assigns it to the StrokeDashes field.
func (o *MinimalStrokesTrait) SetStrokeDashes(v []float32) {
	o.StrokeDashes = v
}

func (o MinimalStrokesTrait) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MinimalStrokesTrait) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Strokes) {
		toSerialize["strokes"] = o.Strokes
	}
	if !IsNil(o.StrokeWeight) {
		toSerialize["strokeWeight"] = o.StrokeWeight
	}
	if !IsNil(o.StrokeAlign) {
		toSerialize["strokeAlign"] = o.StrokeAlign
	}
	if !IsNil(o.StrokeJoin) {
		toSerialize["strokeJoin"] = o.StrokeJoin
	}
	if !IsNil(o.StrokeDashes) {
		toSerialize["strokeDashes"] = o.StrokeDashes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MinimalStrokesTrait) UnmarshalJSON(data []byte) (err error) {
	varMinimalStrokesTrait := _MinimalStrokesTrait{}

	err = json.Unmarshal(data, &varMinimalStrokesTrait)

	if err != nil {
		return err
	}

	*o = MinimalStrokesTrait(varMinimalStrokesTrait)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "strokes")
		delete(additionalProperties, "strokeWeight")
		delete(additionalProperties, "strokeAlign")
		delete(additionalProperties, "strokeJoin")
		delete(additionalProperties, "strokeDashes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMinimalStrokesTrait struct {
	value *MinimalStrokesTrait
	isSet bool
}

func (v NullableMinimalStrokesTrait) Get() *MinimalStrokesTrait {
	return v.value
}

func (v *NullableMinimalStrokesTrait) Set(val *MinimalStrokesTrait) {
	v.value = val
	v.isSet = true
}

func (v NullableMinimalStrokesTrait) IsSet() bool {
	return v.isSet
}

func (v *NullableMinimalStrokesTrait) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinimalStrokesTrait(val *MinimalStrokesTrait) *NullableMinimalStrokesTrait {
	return &NullableMinimalStrokesTrait{value: val, isSet: true}
}

func (v NullableMinimalStrokesTrait) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinimalStrokesTrait) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
