/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InlineObject56 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject56{}

// InlineObject56 struct for InlineObject56
type InlineObject56 struct {
	// Status code
	Status float32 `json:"status"`
	// A string describing the error
	Err string `json:"err"`
}

type _InlineObject56 InlineObject56

// NewInlineObject56 instantiates a new InlineObject56 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject56(status float32, err string) *InlineObject56 {
	this := InlineObject56{}
	this.Status = status
	this.Err = err
	return &this
}

// NewInlineObject56WithDefaults instantiates a new InlineObject56 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject56WithDefaults() *InlineObject56 {
	this := InlineObject56{}
	return &this
}

// GetStatus returns the Status field value
func (o *InlineObject56) GetStatus() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InlineObject56) GetStatusOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InlineObject56) SetStatus(v float32) {
	o.Status = v
}

// GetErr returns the Err field value
func (o *InlineObject56) GetErr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Err
}

// GetErrOk returns a tuple with the Err field value
// and a boolean to check if the value has been set.
func (o *InlineObject56) GetErrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Err, true
}

// SetErr sets field value
func (o *InlineObject56) SetErr(v string) {
	o.Err = v
}

func (o InlineObject56) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject56) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["err"] = o.Err
	return toSerialize, nil
}

func (o *InlineObject56) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"err",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInlineObject56 := _InlineObject56{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInlineObject56)

	if err != nil {
		return err
	}

	*o = InlineObject56(varInlineObject56)

	return err
}

type NullableInlineObject56 struct {
	value *InlineObject56
	isSet bool
}

func (v NullableInlineObject56) Get() *InlineObject56 {
	return v.value
}

func (v *NullableInlineObject56) Set(val *InlineObject56) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject56) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject56) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject56(val *InlineObject56) *NullableInlineObject56 {
	return &NullableInlineObject56{value: val, isSet: true}
}

func (v NullableInlineObject56) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject56) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
