/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConnectorTextBackground type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorTextBackground{}

// ConnectorTextBackground struct for ConnectorTextBackground
type ConnectorTextBackground struct {
	// Radius of each corner if a single radius is set for all corners
	CornerRadius *float32 `json:"cornerRadius,omitempty"`
	// A value that lets you control how \"smooth\" the corners are. Ranges from 0 to 1. 0 is the default and means that the corner is perfectly circular. A value of 0.6 means the corner matches the iOS 7 \"squircle\" icon shape. Other values produce various other curves.
	CornerSmoothing *float32 `json:"cornerSmoothing,omitempty"`
	// Array of length 4 of the radius of each corner of the frame, starting in the top left and proceeding clockwise.  Values are given in the order top-left, top-right, bottom-right, bottom-left.
	RectangleCornerRadii []float32 `json:"rectangleCornerRadii,omitempty"`
	// An array of fill paints applied to the node.
	Fills []Paint `json:"fills"`
	// A mapping of a StyleType to style ID (see Style) of styles present on this node. The style ID can be used to look up more information about the style in the top-level styles field.
	Styles map[string]string `json:"styles,omitempty"`
}

type _ConnectorTextBackground ConnectorTextBackground

// NewConnectorTextBackground instantiates a new ConnectorTextBackground object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorTextBackground(fills []Paint) *ConnectorTextBackground {
	this := ConnectorTextBackground{}
	var cornerRadius float32 = 0
	this.CornerRadius = &cornerRadius
	this.Fills = fills
	return &this
}

// NewConnectorTextBackgroundWithDefaults instantiates a new ConnectorTextBackground object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorTextBackgroundWithDefaults() *ConnectorTextBackground {
	this := ConnectorTextBackground{}
	var cornerRadius float32 = 0
	this.CornerRadius = &cornerRadius
	return &this
}

// GetCornerRadius returns the CornerRadius field value if set, zero value otherwise.
func (o *ConnectorTextBackground) GetCornerRadius() float32 {
	if o == nil || IsNil(o.CornerRadius) {
		var ret float32
		return ret
	}
	return *o.CornerRadius
}

// GetCornerRadiusOk returns a tuple with the CornerRadius field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorTextBackground) GetCornerRadiusOk() (*float32, bool) {
	if o == nil || IsNil(o.CornerRadius) {
		return nil, false
	}
	return o.CornerRadius, true
}

// HasCornerRadius returns a boolean if a field has been set.
func (o *ConnectorTextBackground) HasCornerRadius() bool {
	if o != nil && !IsNil(o.CornerRadius) {
		return true
	}

	return false
}

// SetCornerRadius gets a reference to the given float32 and assigns it to the CornerRadius field.
func (o *ConnectorTextBackground) SetCornerRadius(v float32) {
	o.CornerRadius = &v
}

// GetCornerSmoothing returns the CornerSmoothing field value if set, zero value otherwise.
func (o *ConnectorTextBackground) GetCornerSmoothing() float32 {
	if o == nil || IsNil(o.CornerSmoothing) {
		var ret float32
		return ret
	}
	return *o.CornerSmoothing
}

// GetCornerSmoothingOk returns a tuple with the CornerSmoothing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorTextBackground) GetCornerSmoothingOk() (*float32, bool) {
	if o == nil || IsNil(o.CornerSmoothing) {
		return nil, false
	}
	return o.CornerSmoothing, true
}

// HasCornerSmoothing returns a boolean if a field has been set.
func (o *ConnectorTextBackground) HasCornerSmoothing() bool {
	if o != nil && !IsNil(o.CornerSmoothing) {
		return true
	}

	return false
}

// SetCornerSmoothing gets a reference to the given float32 and assigns it to the CornerSmoothing field.
func (o *ConnectorTextBackground) SetCornerSmoothing(v float32) {
	o.CornerSmoothing = &v
}

// GetRectangleCornerRadii returns the RectangleCornerRadii field value if set, zero value otherwise.
func (o *ConnectorTextBackground) GetRectangleCornerRadii() []float32 {
	if o == nil || IsNil(o.RectangleCornerRadii) {
		var ret []float32
		return ret
	}
	return o.RectangleCornerRadii
}

// GetRectangleCornerRadiiOk returns a tuple with the RectangleCornerRadii field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorTextBackground) GetRectangleCornerRadiiOk() ([]float32, bool) {
	if o == nil || IsNil(o.RectangleCornerRadii) {
		return nil, false
	}
	return o.RectangleCornerRadii, true
}

// HasRectangleCornerRadii returns a boolean if a field has been set.
func (o *ConnectorTextBackground) HasRectangleCornerRadii() bool {
	if o != nil && !IsNil(o.RectangleCornerRadii) {
		return true
	}

	return false
}

// SetRectangleCornerRadii gets a reference to the given []float32 and assigns it to the RectangleCornerRadii field.
func (o *ConnectorTextBackground) SetRectangleCornerRadii(v []float32) {
	o.RectangleCornerRadii = v
}

// GetFills returns the Fills field value
func (o *ConnectorTextBackground) GetFills() []Paint {
	if o == nil {
		var ret []Paint
		return ret
	}

	return o.Fills
}

// GetFillsOk returns a tuple with the Fills field value
// and a boolean to check if the value has been set.
func (o *ConnectorTextBackground) GetFillsOk() ([]Paint, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fills, true
}

// SetFills sets field value
func (o *ConnectorTextBackground) SetFills(v []Paint) {
	o.Fills = v
}

// GetStyles returns the Styles field value if set, zero value otherwise.
func (o *ConnectorTextBackground) GetStyles() map[string]string {
	if o == nil || IsNil(o.Styles) {
		var ret map[string]string
		return ret
	}
	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorTextBackground) GetStylesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Styles) {
		return map[string]string{}, false
	}
	return o.Styles, true
}

// HasStyles returns a boolean if a field has been set.
func (o *ConnectorTextBackground) HasStyles() bool {
	if o != nil && !IsNil(o.Styles) {
		return true
	}

	return false
}

// SetStyles gets a reference to the given map[string]string and assigns it to the Styles field.
func (o *ConnectorTextBackground) SetStyles(v map[string]string) {
	o.Styles = v
}

func (o ConnectorTextBackground) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorTextBackground) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CornerRadius) {
		toSerialize["cornerRadius"] = o.CornerRadius
	}
	if !IsNil(o.CornerSmoothing) {
		toSerialize["cornerSmoothing"] = o.CornerSmoothing
	}
	if !IsNil(o.RectangleCornerRadii) {
		toSerialize["rectangleCornerRadii"] = o.RectangleCornerRadii
	}
	toSerialize["fills"] = o.Fills
	if !IsNil(o.Styles) {
		toSerialize["styles"] = o.Styles
	}
	return toSerialize, nil
}

func (o *ConnectorTextBackground) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fills",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorTextBackground := _ConnectorTextBackground{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectorTextBackground)

	if err != nil {
		return err
	}

	*o = ConnectorTextBackground(varConnectorTextBackground)

	return err
}

type NullableConnectorTextBackground struct {
	value *ConnectorTextBackground
	isSet bool
}

func (v NullableConnectorTextBackground) Get() *ConnectorTextBackground {
	return v.value
}

func (v *NullableConnectorTextBackground) Set(val *ConnectorTextBackground) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorTextBackground) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorTextBackground) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorTextBackground(val *ConnectorTextBackground) *NullableConnectorTextBackground {
	return &NullableConnectorTextBackground{value: val, isSet: true}
}

func (v NullableConnectorTextBackground) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorTextBackground) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
