/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
	"fmt"
)

// checks if the ErrorResponsePayloadWithErrMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorResponsePayloadWithErrMessage{}

// ErrorResponsePayloadWithErrMessage A response indicating an error occurred.
type ErrorResponsePayloadWithErrMessage struct {
	// Status code
	Status float32 `json:"status"`
	// A string describing the error
	Err                  string `json:"err"`
	AdditionalProperties map[string]interface{}
}

type _ErrorResponsePayloadWithErrMessage ErrorResponsePayloadWithErrMessage

// NewErrorResponsePayloadWithErrMessage instantiates a new ErrorResponsePayloadWithErrMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorResponsePayloadWithErrMessage(status float32, err string) *ErrorResponsePayloadWithErrMessage {
	this := ErrorResponsePayloadWithErrMessage{}
	this.Status = status
	this.Err = err
	return &this
}

// NewErrorResponsePayloadWithErrMessageWithDefaults instantiates a new ErrorResponsePayloadWithErrMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorResponsePayloadWithErrMessageWithDefaults() *ErrorResponsePayloadWithErrMessage {
	this := ErrorResponsePayloadWithErrMessage{}
	return &this
}

// GetStatus returns the Status field value
func (o *ErrorResponsePayloadWithErrMessage) GetStatus() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ErrorResponsePayloadWithErrMessage) GetStatusOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ErrorResponsePayloadWithErrMessage) SetStatus(v float32) {
	o.Status = v
}

// GetErr returns the Err field value
func (o *ErrorResponsePayloadWithErrMessage) GetErr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Err
}

// GetErrOk returns a tuple with the Err field value
// and a boolean to check if the value has been set.
func (o *ErrorResponsePayloadWithErrMessage) GetErrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Err, true
}

// SetErr sets field value
func (o *ErrorResponsePayloadWithErrMessage) SetErr(v string) {
	o.Err = v
}

func (o ErrorResponsePayloadWithErrMessage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorResponsePayloadWithErrMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["err"] = o.Err

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ErrorResponsePayloadWithErrMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"err",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorResponsePayloadWithErrMessage := _ErrorResponsePayloadWithErrMessage{}

	err = json.Unmarshal(data, &varErrorResponsePayloadWithErrMessage)

	if err != nil {
		return err
	}

	*o = ErrorResponsePayloadWithErrMessage(varErrorResponsePayloadWithErrMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "err")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableErrorResponsePayloadWithErrMessage struct {
	value *ErrorResponsePayloadWithErrMessage
	isSet bool
}

func (v NullableErrorResponsePayloadWithErrMessage) Get() *ErrorResponsePayloadWithErrMessage {
	return v.value
}

func (v *NullableErrorResponsePayloadWithErrMessage) Set(val *ErrorResponsePayloadWithErrMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorResponsePayloadWithErrMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorResponsePayloadWithErrMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorResponsePayloadWithErrMessage(val *ErrorResponsePayloadWithErrMessage) *NullableErrorResponsePayloadWithErrMessage {
	return &NullableErrorResponsePayloadWithErrMessage{value: val, isSet: true}
}

func (v NullableErrorResponsePayloadWithErrMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorResponsePayloadWithErrMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
