/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
)

// checks if the TextPathTypeStyle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextPathTypeStyle{}

// TextPathTypeStyle struct for TextPathTypeStyle
type TextPathTypeStyle struct {
	// Font family of text (standard name).
	FontFamily *string `json:"fontFamily,omitempty"`
	// PostScript font name.
	FontPostScriptName *string `json:"fontPostScriptName,omitempty"`
	// Describes visual weight or emphasis, such as Bold or Italic.
	FontStyle *string `json:"fontStyle,omitempty"`
	// Whether or not text is italicized.
	Italic *bool `json:"italic,omitempty"`
	// Numeric font weight.
	FontWeight *float32 `json:"fontWeight,omitempty"`
	// Font size in px.
	FontSize *float32 `json:"fontSize,omitempty"`
	// Text casing applied to the node, default is the original casing.
	TextCase *string `json:"textCase,omitempty"`
	// Horizontal text alignment as string enum.
	TextAlignHorizontal *string `json:"textAlignHorizontal,omitempty"`
	// Vertical text alignment as string enum.
	TextAlignVertical *string `json:"textAlignVertical,omitempty"`
	// Space between characters in px.
	LetterSpacing *float32 `json:"letterSpacing,omitempty"`
	// An array of fill paints applied to the characters.
	Fills []Paint `json:"fills,omitempty"`
	// Link to a URL or frame.
	Hyperlink *Hyperlink `json:"hyperlink,omitempty"`
	// A map of OpenType feature flags to 1 or 0, 1 if it is enabled and 0 if it is disabled. Note that some flags aren't reflected here. For example, SMCP (small caps) is still represented by the `textCase` field.
	OpentypeFlags map[string]float32 `json:"opentypeFlags,omitempty"`
	// Indicates how the font weight was overridden when there is a text style override.
	SemanticWeight *string `json:"semanticWeight,omitempty"`
	// Indicates how the font style was overridden when there is a text style override.
	SemanticItalic *string `json:"semanticItalic,omitempty"`
	// Whether or not this style has overrides over a text style. The possible fields to override are semanticWeight, semanticItalic, and hyperlink. If this is true, then those fields are overrides if present.
	IsOverrideOverTextStyle *bool                                 `json:"isOverrideOverTextStyle,omitempty"`
	BoundVariables          *TextPathTypeStyleAllOfBoundVariables `json:"boundVariables,omitempty"`
	AdditionalProperties    map[string]interface{}
}

type _TextPathTypeStyle TextPathTypeStyle

// NewTextPathTypeStyle instantiates a new TextPathTypeStyle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextPathTypeStyle() *TextPathTypeStyle {
	this := TextPathTypeStyle{}
	var italic bool = false
	this.Italic = &italic
	return &this
}

// NewTextPathTypeStyleWithDefaults instantiates a new TextPathTypeStyle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextPathTypeStyleWithDefaults() *TextPathTypeStyle {
	this := TextPathTypeStyle{}
	var italic bool = false
	this.Italic = &italic
	return &this
}

// GetFontFamily returns the FontFamily field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetFontFamily() string {
	if o == nil || IsNil(o.FontFamily) {
		var ret string
		return ret
	}
	return *o.FontFamily
}

// GetFontFamilyOk returns a tuple with the FontFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetFontFamilyOk() (*string, bool) {
	if o == nil || IsNil(o.FontFamily) {
		return nil, false
	}
	return o.FontFamily, true
}

// HasFontFamily returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasFontFamily() bool {
	if o != nil && !IsNil(o.FontFamily) {
		return true
	}

	return false
}

// SetFontFamily gets a reference to the given string and assigns it to the FontFamily field.
func (o *TextPathTypeStyle) SetFontFamily(v string) {
	o.FontFamily = &v
}

// GetFontPostScriptName returns the FontPostScriptName field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetFontPostScriptName() string {
	if o == nil || IsNil(o.FontPostScriptName) {
		var ret string
		return ret
	}
	return *o.FontPostScriptName
}

// GetFontPostScriptNameOk returns a tuple with the FontPostScriptName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetFontPostScriptNameOk() (*string, bool) {
	if o == nil || IsNil(o.FontPostScriptName) {
		return nil, false
	}
	return o.FontPostScriptName, true
}

// HasFontPostScriptName returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasFontPostScriptName() bool {
	if o != nil && !IsNil(o.FontPostScriptName) {
		return true
	}

	return false
}

// SetFontPostScriptName gets a reference to the given string and assigns it to the FontPostScriptName field.
func (o *TextPathTypeStyle) SetFontPostScriptName(v string) {
	o.FontPostScriptName = &v
}

// GetFontStyle returns the FontStyle field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetFontStyle() string {
	if o == nil || IsNil(o.FontStyle) {
		var ret string
		return ret
	}
	return *o.FontStyle
}

// GetFontStyleOk returns a tuple with the FontStyle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetFontStyleOk() (*string, bool) {
	if o == nil || IsNil(o.FontStyle) {
		return nil, false
	}
	return o.FontStyle, true
}

// HasFontStyle returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasFontStyle() bool {
	if o != nil && !IsNil(o.FontStyle) {
		return true
	}

	return false
}

// SetFontStyle gets a reference to the given string and assigns it to the FontStyle field.
func (o *TextPathTypeStyle) SetFontStyle(v string) {
	o.FontStyle = &v
}

// GetItalic returns the Italic field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetItalic() bool {
	if o == nil || IsNil(o.Italic) {
		var ret bool
		return ret
	}
	return *o.Italic
}

// GetItalicOk returns a tuple with the Italic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetItalicOk() (*bool, bool) {
	if o == nil || IsNil(o.Italic) {
		return nil, false
	}
	return o.Italic, true
}

// HasItalic returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasItalic() bool {
	if o != nil && !IsNil(o.Italic) {
		return true
	}

	return false
}

// SetItalic gets a reference to the given bool and assigns it to the Italic field.
func (o *TextPathTypeStyle) SetItalic(v bool) {
	o.Italic = &v
}

// GetFontWeight returns the FontWeight field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetFontWeight() float32 {
	if o == nil || IsNil(o.FontWeight) {
		var ret float32
		return ret
	}
	return *o.FontWeight
}

// GetFontWeightOk returns a tuple with the FontWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetFontWeightOk() (*float32, bool) {
	if o == nil || IsNil(o.FontWeight) {
		return nil, false
	}
	return o.FontWeight, true
}

// HasFontWeight returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasFontWeight() bool {
	if o != nil && !IsNil(o.FontWeight) {
		return true
	}

	return false
}

// SetFontWeight gets a reference to the given float32 and assigns it to the FontWeight field.
func (o *TextPathTypeStyle) SetFontWeight(v float32) {
	o.FontWeight = &v
}

// GetFontSize returns the FontSize field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetFontSize() float32 {
	if o == nil || IsNil(o.FontSize) {
		var ret float32
		return ret
	}
	return *o.FontSize
}

// GetFontSizeOk returns a tuple with the FontSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetFontSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.FontSize) {
		return nil, false
	}
	return o.FontSize, true
}

// HasFontSize returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasFontSize() bool {
	if o != nil && !IsNil(o.FontSize) {
		return true
	}

	return false
}

// SetFontSize gets a reference to the given float32 and assigns it to the FontSize field.
func (o *TextPathTypeStyle) SetFontSize(v float32) {
	o.FontSize = &v
}

// GetTextCase returns the TextCase field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetTextCase() string {
	if o == nil || IsNil(o.TextCase) {
		var ret string
		return ret
	}
	return *o.TextCase
}

// GetTextCaseOk returns a tuple with the TextCase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetTextCaseOk() (*string, bool) {
	if o == nil || IsNil(o.TextCase) {
		return nil, false
	}
	return o.TextCase, true
}

// HasTextCase returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasTextCase() bool {
	if o != nil && !IsNil(o.TextCase) {
		return true
	}

	return false
}

// SetTextCase gets a reference to the given string and assigns it to the TextCase field.
func (o *TextPathTypeStyle) SetTextCase(v string) {
	o.TextCase = &v
}

// GetTextAlignHorizontal returns the TextAlignHorizontal field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetTextAlignHorizontal() string {
	if o == nil || IsNil(o.TextAlignHorizontal) {
		var ret string
		return ret
	}
	return *o.TextAlignHorizontal
}

// GetTextAlignHorizontalOk returns a tuple with the TextAlignHorizontal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetTextAlignHorizontalOk() (*string, bool) {
	if o == nil || IsNil(o.TextAlignHorizontal) {
		return nil, false
	}
	return o.TextAlignHorizontal, true
}

// HasTextAlignHorizontal returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasTextAlignHorizontal() bool {
	if o != nil && !IsNil(o.TextAlignHorizontal) {
		return true
	}

	return false
}

// SetTextAlignHorizontal gets a reference to the given string and assigns it to the TextAlignHorizontal field.
func (o *TextPathTypeStyle) SetTextAlignHorizontal(v string) {
	o.TextAlignHorizontal = &v
}

// GetTextAlignVertical returns the TextAlignVertical field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetTextAlignVertical() string {
	if o == nil || IsNil(o.TextAlignVertical) {
		var ret string
		return ret
	}
	return *o.TextAlignVertical
}

// GetTextAlignVerticalOk returns a tuple with the TextAlignVertical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetTextAlignVerticalOk() (*string, bool) {
	if o == nil || IsNil(o.TextAlignVertical) {
		return nil, false
	}
	return o.TextAlignVertical, true
}

// HasTextAlignVertical returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasTextAlignVertical() bool {
	if o != nil && !IsNil(o.TextAlignVertical) {
		return true
	}

	return false
}

// SetTextAlignVertical gets a reference to the given string and assigns it to the TextAlignVertical field.
func (o *TextPathTypeStyle) SetTextAlignVertical(v string) {
	o.TextAlignVertical = &v
}

// GetLetterSpacing returns the LetterSpacing field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetLetterSpacing() float32 {
	if o == nil || IsNil(o.LetterSpacing) {
		var ret float32
		return ret
	}
	return *o.LetterSpacing
}

// GetLetterSpacingOk returns a tuple with the LetterSpacing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetLetterSpacingOk() (*float32, bool) {
	if o == nil || IsNil(o.LetterSpacing) {
		return nil, false
	}
	return o.LetterSpacing, true
}

// HasLetterSpacing returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasLetterSpacing() bool {
	if o != nil && !IsNil(o.LetterSpacing) {
		return true
	}

	return false
}

// SetLetterSpacing gets a reference to the given float32 and assigns it to the LetterSpacing field.
func (o *TextPathTypeStyle) SetLetterSpacing(v float32) {
	o.LetterSpacing = &v
}

// GetFills returns the Fills field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetFills() []Paint {
	if o == nil || IsNil(o.Fills) {
		var ret []Paint
		return ret
	}
	return o.Fills
}

// GetFillsOk returns a tuple with the Fills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetFillsOk() ([]Paint, bool) {
	if o == nil || IsNil(o.Fills) {
		return nil, false
	}
	return o.Fills, true
}

// HasFills returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasFills() bool {
	if o != nil && !IsNil(o.Fills) {
		return true
	}

	return false
}

// SetFills gets a reference to the given []Paint and assigns it to the Fills field.
func (o *TextPathTypeStyle) SetFills(v []Paint) {
	o.Fills = v
}

// GetHyperlink returns the Hyperlink field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetHyperlink() Hyperlink {
	if o == nil || IsNil(o.Hyperlink) {
		var ret Hyperlink
		return ret
	}
	return *o.Hyperlink
}

// GetHyperlinkOk returns a tuple with the Hyperlink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetHyperlinkOk() (*Hyperlink, bool) {
	if o == nil || IsNil(o.Hyperlink) {
		return nil, false
	}
	return o.Hyperlink, true
}

// HasHyperlink returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasHyperlink() bool {
	if o != nil && !IsNil(o.Hyperlink) {
		return true
	}

	return false
}

// SetHyperlink gets a reference to the given Hyperlink and assigns it to the Hyperlink field.
func (o *TextPathTypeStyle) SetHyperlink(v Hyperlink) {
	o.Hyperlink = &v
}

// GetOpentypeFlags returns the OpentypeFlags field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetOpentypeFlags() map[string]float32 {
	if o == nil || IsNil(o.OpentypeFlags) {
		var ret map[string]float32
		return ret
	}
	return o.OpentypeFlags
}

// GetOpentypeFlagsOk returns a tuple with the OpentypeFlags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetOpentypeFlagsOk() (map[string]float32, bool) {
	if o == nil || IsNil(o.OpentypeFlags) {
		return map[string]float32{}, false
	}
	return o.OpentypeFlags, true
}

// HasOpentypeFlags returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasOpentypeFlags() bool {
	if o != nil && !IsNil(o.OpentypeFlags) {
		return true
	}

	return false
}

// SetOpentypeFlags gets a reference to the given map[string]float32 and assigns it to the OpentypeFlags field.
func (o *TextPathTypeStyle) SetOpentypeFlags(v map[string]float32) {
	o.OpentypeFlags = v
}

// GetSemanticWeight returns the SemanticWeight field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetSemanticWeight() string {
	if o == nil || IsNil(o.SemanticWeight) {
		var ret string
		return ret
	}
	return *o.SemanticWeight
}

// GetSemanticWeightOk returns a tuple with the SemanticWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetSemanticWeightOk() (*string, bool) {
	if o == nil || IsNil(o.SemanticWeight) {
		return nil, false
	}
	return o.SemanticWeight, true
}

// HasSemanticWeight returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasSemanticWeight() bool {
	if o != nil && !IsNil(o.SemanticWeight) {
		return true
	}

	return false
}

// SetSemanticWeight gets a reference to the given string and assigns it to the SemanticWeight field.
func (o *TextPathTypeStyle) SetSemanticWeight(v string) {
	o.SemanticWeight = &v
}

// GetSemanticItalic returns the SemanticItalic field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetSemanticItalic() string {
	if o == nil || IsNil(o.SemanticItalic) {
		var ret string
		return ret
	}
	return *o.SemanticItalic
}

// GetSemanticItalicOk returns a tuple with the SemanticItalic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetSemanticItalicOk() (*string, bool) {
	if o == nil || IsNil(o.SemanticItalic) {
		return nil, false
	}
	return o.SemanticItalic, true
}

// HasSemanticItalic returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasSemanticItalic() bool {
	if o != nil && !IsNil(o.SemanticItalic) {
		return true
	}

	return false
}

// SetSemanticItalic gets a reference to the given string and assigns it to the SemanticItalic field.
func (o *TextPathTypeStyle) SetSemanticItalic(v string) {
	o.SemanticItalic = &v
}

// GetIsOverrideOverTextStyle returns the IsOverrideOverTextStyle field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetIsOverrideOverTextStyle() bool {
	if o == nil || IsNil(o.IsOverrideOverTextStyle) {
		var ret bool
		return ret
	}
	return *o.IsOverrideOverTextStyle
}

// GetIsOverrideOverTextStyleOk returns a tuple with the IsOverrideOverTextStyle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetIsOverrideOverTextStyleOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOverrideOverTextStyle) {
		return nil, false
	}
	return o.IsOverrideOverTextStyle, true
}

// HasIsOverrideOverTextStyle returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasIsOverrideOverTextStyle() bool {
	if o != nil && !IsNil(o.IsOverrideOverTextStyle) {
		return true
	}

	return false
}

// SetIsOverrideOverTextStyle gets a reference to the given bool and assigns it to the IsOverrideOverTextStyle field.
func (o *TextPathTypeStyle) SetIsOverrideOverTextStyle(v bool) {
	o.IsOverrideOverTextStyle = &v
}

// GetBoundVariables returns the BoundVariables field value if set, zero value otherwise.
func (o *TextPathTypeStyle) GetBoundVariables() TextPathTypeStyleAllOfBoundVariables {
	if o == nil || IsNil(o.BoundVariables) {
		var ret TextPathTypeStyleAllOfBoundVariables
		return ret
	}
	return *o.BoundVariables
}

// GetBoundVariablesOk returns a tuple with the BoundVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextPathTypeStyle) GetBoundVariablesOk() (*TextPathTypeStyleAllOfBoundVariables, bool) {
	if o == nil || IsNil(o.BoundVariables) {
		return nil, false
	}
	return o.BoundVariables, true
}

// HasBoundVariables returns a boolean if a field has been set.
func (o *TextPathTypeStyle) HasBoundVariables() bool {
	if o != nil && !IsNil(o.BoundVariables) {
		return true
	}

	return false
}

// SetBoundVariables gets a reference to the given TextPathTypeStyleAllOfBoundVariables and assigns it to the BoundVariables field.
func (o *TextPathTypeStyle) SetBoundVariables(v TextPathTypeStyleAllOfBoundVariables) {
	o.BoundVariables = &v
}

func (o TextPathTypeStyle) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextPathTypeStyle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FontFamily) {
		toSerialize["fontFamily"] = o.FontFamily
	}
	if !IsNil(o.FontPostScriptName) {
		toSerialize["fontPostScriptName"] = o.FontPostScriptName
	}
	if !IsNil(o.FontStyle) {
		toSerialize["fontStyle"] = o.FontStyle
	}
	if !IsNil(o.Italic) {
		toSerialize["italic"] = o.Italic
	}
	if !IsNil(o.FontWeight) {
		toSerialize["fontWeight"] = o.FontWeight
	}
	if !IsNil(o.FontSize) {
		toSerialize["fontSize"] = o.FontSize
	}
	if !IsNil(o.TextCase) {
		toSerialize["textCase"] = o.TextCase
	}
	if !IsNil(o.TextAlignHorizontal) {
		toSerialize["textAlignHorizontal"] = o.TextAlignHorizontal
	}
	if !IsNil(o.TextAlignVertical) {
		toSerialize["textAlignVertical"] = o.TextAlignVertical
	}
	if !IsNil(o.LetterSpacing) {
		toSerialize["letterSpacing"] = o.LetterSpacing
	}
	if !IsNil(o.Fills) {
		toSerialize["fills"] = o.Fills
	}
	if !IsNil(o.Hyperlink) {
		toSerialize["hyperlink"] = o.Hyperlink
	}
	if !IsNil(o.OpentypeFlags) {
		toSerialize["opentypeFlags"] = o.OpentypeFlags
	}
	if !IsNil(o.SemanticWeight) {
		toSerialize["semanticWeight"] = o.SemanticWeight
	}
	if !IsNil(o.SemanticItalic) {
		toSerialize["semanticItalic"] = o.SemanticItalic
	}
	if !IsNil(o.IsOverrideOverTextStyle) {
		toSerialize["isOverrideOverTextStyle"] = o.IsOverrideOverTextStyle
	}
	if !IsNil(o.BoundVariables) {
		toSerialize["boundVariables"] = o.BoundVariables
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TextPathTypeStyle) UnmarshalJSON(data []byte) (err error) {
	varTextPathTypeStyle := _TextPathTypeStyle{}

	err = json.Unmarshal(data, &varTextPathTypeStyle)

	if err != nil {
		return err
	}

	*o = TextPathTypeStyle(varTextPathTypeStyle)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fontFamily")
		delete(additionalProperties, "fontPostScriptName")
		delete(additionalProperties, "fontStyle")
		delete(additionalProperties, "italic")
		delete(additionalProperties, "fontWeight")
		delete(additionalProperties, "fontSize")
		delete(additionalProperties, "textCase")
		delete(additionalProperties, "textAlignHorizontal")
		delete(additionalProperties, "textAlignVertical")
		delete(additionalProperties, "letterSpacing")
		delete(additionalProperties, "fills")
		delete(additionalProperties, "hyperlink")
		delete(additionalProperties, "opentypeFlags")
		delete(additionalProperties, "semanticWeight")
		delete(additionalProperties, "semanticItalic")
		delete(additionalProperties, "isOverrideOverTextStyle")
		delete(additionalProperties, "boundVariables")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTextPathTypeStyle struct {
	value *TextPathTypeStyle
	isSet bool
}

func (v NullableTextPathTypeStyle) Get() *TextPathTypeStyle {
	return v.value
}

func (v *NullableTextPathTypeStyle) Set(val *TextPathTypeStyle) {
	v.value = val
	v.isSet = true
}

func (v NullableTextPathTypeStyle) IsSet() bool {
	return v.isSet
}

func (v *NullableTextPathTypeStyle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextPathTypeStyle(val *TextPathTypeStyle) *NullableTextPathTypeStyle {
	return &NullableTextPathTypeStyle{value: val, isSet: true}
}

func (v NullableTextPathTypeStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextPathTypeStyle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
