/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
	"fmt"
)

// checks if the TriggerOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerOneOf2{}

// TriggerOneOf2 struct for TriggerOneOf2
type TriggerOneOf2 struct {
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _TriggerOneOf2 TriggerOneOf2

// NewTriggerOneOf2 instantiates a new TriggerOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerOneOf2(type_ string) *TriggerOneOf2 {
	this := TriggerOneOf2{}
	this.Type = type_
	return &this
}

// NewTriggerOneOf2WithDefaults instantiates a new TriggerOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerOneOf2WithDefaults() *TriggerOneOf2 {
	this := TriggerOneOf2{}
	return &this
}

// GetType returns the Type field value
func (o *TriggerOneOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TriggerOneOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TriggerOneOf2) SetType(v string) {
	o.Type = v
}

func (o TriggerOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TriggerOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTriggerOneOf2 := _TriggerOneOf2{}

	err = json.Unmarshal(data, &varTriggerOneOf2)

	if err != nil {
		return err
	}

	*o = TriggerOneOf2(varTriggerOneOf2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTriggerOneOf2 struct {
	value *TriggerOneOf2
	isSet bool
}

func (v NullableTriggerOneOf2) Get() *TriggerOneOf2 {
	return v.value
}

func (v *NullableTriggerOneOf2) Set(val *TriggerOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerOneOf2(val *TriggerOneOf2) *NullableTriggerOneOf2 {
	return &NullableTriggerOneOf2{value: val, isSet: true}
}

func (v NullableTriggerOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
