/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
	"fmt"
)

// Paint - struct for Paint
type Paint struct {
	GradientPaint *GradientPaint
	ImagePaint    *ImagePaint
	PatternPaint  *PatternPaint
	SolidPaint    *SolidPaint
}

// GradientPaintAsPaint is a convenience function that returns GradientPaint wrapped in Paint
func GradientPaintAsPaint(v *GradientPaint) Paint {
	return Paint{
		GradientPaint: v,
	}
}

// ImagePaintAsPaint is a convenience function that returns ImagePaint wrapped in Paint
func ImagePaintAsPaint(v *ImagePaint) Paint {
	return Paint{
		ImagePaint: v,
	}
}

// PatternPaintAsPaint is a convenience function that returns PatternPaint wrapped in Paint
func PatternPaintAsPaint(v *PatternPaint) Paint {
	return Paint{
		PatternPaint: v,
	}
}

// SolidPaintAsPaint is a convenience function that returns SolidPaint wrapped in Paint
func SolidPaintAsPaint(v *SolidPaint) Paint {
	return Paint{
		SolidPaint: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Paint) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GradientPaint
	err = json.Unmarshal(data, &dst.GradientPaint)
	if err == nil {
		jsonGradientPaint, _ := json.Marshal(dst.GradientPaint)
		if string(jsonGradientPaint) == "{}" { // empty struct
			dst.GradientPaint = nil
		} else {
			match++
		}
	} else {
		dst.GradientPaint = nil
	}

	// try to unmarshal data into ImagePaint
	err = json.Unmarshal(data, &dst.ImagePaint)
	if err == nil {
		jsonImagePaint, _ := json.Marshal(dst.ImagePaint)
		if string(jsonImagePaint) == "{}" { // empty struct
			dst.ImagePaint = nil
		} else {
			match++
		}
	} else {
		dst.ImagePaint = nil
	}

	// try to unmarshal data into PatternPaint
	err = json.Unmarshal(data, &dst.PatternPaint)
	if err == nil {
		jsonPatternPaint, _ := json.Marshal(dst.PatternPaint)
		if string(jsonPatternPaint) == "{}" { // empty struct
			dst.PatternPaint = nil
		} else {
			match++
		}
	} else {
		dst.PatternPaint = nil
	}

	// try to unmarshal data into SolidPaint
	err = json.Unmarshal(data, &dst.SolidPaint)
	if err == nil {
		jsonSolidPaint, _ := json.Marshal(dst.SolidPaint)
		if string(jsonSolidPaint) == "{}" { // empty struct
			dst.SolidPaint = nil
		} else {
			match++
		}
	} else {
		dst.SolidPaint = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GradientPaint = nil
		dst.ImagePaint = nil
		dst.PatternPaint = nil
		dst.SolidPaint = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Paint)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(Paint): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(Paint)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Paint) MarshalJSON() ([]byte, error) {
	if src.GradientPaint != nil {
		return json.Marshal(&src.GradientPaint)
	}

	if src.ImagePaint != nil {
		return json.Marshal(&src.ImagePaint)
	}

	if src.PatternPaint != nil {
		return json.Marshal(&src.PatternPaint)
	}

	if src.SolidPaint != nil {
		return json.Marshal(&src.SolidPaint)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Paint) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.GradientPaint != nil {
		return obj.GradientPaint
	}

	if obj.ImagePaint != nil {
		return obj.ImagePaint
	}

	if obj.PatternPaint != nil {
		return obj.PatternPaint
	}

	if obj.SolidPaint != nil {
		return obj.SolidPaint
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Paint) GetActualInstanceValue() interface{} {
	if obj.GradientPaint != nil {
		return *obj.GradientPaint
	}

	if obj.ImagePaint != nil {
		return *obj.ImagePaint
	}

	if obj.PatternPaint != nil {
		return *obj.PatternPaint
	}

	if obj.SolidPaint != nil {
		return *obj.SolidPaint
	}

	// all schemas are nil
	return nil
}

type NullablePaint struct {
	value *Paint
	isSet bool
}

func (v NullablePaint) Get() *Paint {
	return v.value
}

func (v *NullablePaint) Set(val *Paint) {
	v.value = val
	v.isSet = true
}

func (v NullablePaint) IsSet() bool {
	return v.isSet
}

func (v *NullablePaint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaint(val *Paint) *NullablePaint {
	return &NullablePaint{value: val, isSet: true}
}

func (v NullablePaint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
