/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NormalBlurEffect type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NormalBlurEffect{}

// NormalBlurEffect struct for NormalBlurEffect
type NormalBlurEffect struct {
	// A string literal representing the effect's type. Always check the type before reading other properties.
	Type string `json:"type"`
	// Whether this blur is active.
	Visible bool `json:"visible"`
	// Radius of the blur effect
	Radius         float32                       `json:"radius"`
	BoundVariables *BaseBlurEffectBoundVariables `json:"boundVariables,omitempty"`
	// The string literal 'NORMAL' representing the blur type. Always check the blurType before reading other properties.
	BlurType *string `json:"blurType,omitempty"`
}

type _NormalBlurEffect NormalBlurEffect

// NewNormalBlurEffect instantiates a new NormalBlurEffect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNormalBlurEffect(type_ string, visible bool, radius float32) *NormalBlurEffect {
	this := NormalBlurEffect{}
	this.Type = type_
	this.Visible = visible
	this.Radius = radius
	return &this
}

// NewNormalBlurEffectWithDefaults instantiates a new NormalBlurEffect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNormalBlurEffectWithDefaults() *NormalBlurEffect {
	this := NormalBlurEffect{}
	return &this
}

// GetType returns the Type field value
func (o *NormalBlurEffect) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NormalBlurEffect) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NormalBlurEffect) SetType(v string) {
	o.Type = v
}

// GetVisible returns the Visible field value
func (o *NormalBlurEffect) GetVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value
// and a boolean to check if the value has been set.
func (o *NormalBlurEffect) GetVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visible, true
}

// SetVisible sets field value
func (o *NormalBlurEffect) SetVisible(v bool) {
	o.Visible = v
}

// GetRadius returns the Radius field value
func (o *NormalBlurEffect) GetRadius() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Radius
}

// GetRadiusOk returns a tuple with the Radius field value
// and a boolean to check if the value has been set.
func (o *NormalBlurEffect) GetRadiusOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Radius, true
}

// SetRadius sets field value
func (o *NormalBlurEffect) SetRadius(v float32) {
	o.Radius = v
}

// GetBoundVariables returns the BoundVariables field value if set, zero value otherwise.
func (o *NormalBlurEffect) GetBoundVariables() BaseBlurEffectBoundVariables {
	if o == nil || IsNil(o.BoundVariables) {
		var ret BaseBlurEffectBoundVariables
		return ret
	}
	return *o.BoundVariables
}

// GetBoundVariablesOk returns a tuple with the BoundVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalBlurEffect) GetBoundVariablesOk() (*BaseBlurEffectBoundVariables, bool) {
	if o == nil || IsNil(o.BoundVariables) {
		return nil, false
	}
	return o.BoundVariables, true
}

// HasBoundVariables returns a boolean if a field has been set.
func (o *NormalBlurEffect) HasBoundVariables() bool {
	if o != nil && !IsNil(o.BoundVariables) {
		return true
	}

	return false
}

// SetBoundVariables gets a reference to the given BaseBlurEffectBoundVariables and assigns it to the BoundVariables field.
func (o *NormalBlurEffect) SetBoundVariables(v BaseBlurEffectBoundVariables) {
	o.BoundVariables = &v
}

// GetBlurType returns the BlurType field value if set, zero value otherwise.
func (o *NormalBlurEffect) GetBlurType() string {
	if o == nil || IsNil(o.BlurType) {
		var ret string
		return ret
	}
	return *o.BlurType
}

// GetBlurTypeOk returns a tuple with the BlurType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalBlurEffect) GetBlurTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BlurType) {
		return nil, false
	}
	return o.BlurType, true
}

// HasBlurType returns a boolean if a field has been set.
func (o *NormalBlurEffect) HasBlurType() bool {
	if o != nil && !IsNil(o.BlurType) {
		return true
	}

	return false
}

// SetBlurType gets a reference to the given string and assigns it to the BlurType field.
func (o *NormalBlurEffect) SetBlurType(v string) {
	o.BlurType = &v
}

func (o NormalBlurEffect) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NormalBlurEffect) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["visible"] = o.Visible
	toSerialize["radius"] = o.Radius
	if !IsNil(o.BoundVariables) {
		toSerialize["boundVariables"] = o.BoundVariables
	}
	if !IsNil(o.BlurType) {
		toSerialize["blurType"] = o.BlurType
	}
	return toSerialize, nil
}

func (o *NormalBlurEffect) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"visible",
		"radius",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNormalBlurEffect := _NormalBlurEffect{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNormalBlurEffect)

	if err != nil {
		return err
	}

	*o = NormalBlurEffect(varNormalBlurEffect)

	return err
}

type NullableNormalBlurEffect struct {
	value *NormalBlurEffect
	isSet bool
}

func (v NullableNormalBlurEffect) Get() *NormalBlurEffect {
	return v.value
}

func (v *NullableNormalBlurEffect) Set(val *NormalBlurEffect) {
	v.value = val
	v.isSet = true
}

func (v NullableNormalBlurEffect) IsSet() bool {
	return v.isSet
}

func (v *NullableNormalBlurEffect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNormalBlurEffect(val *NormalBlurEffect) *NullableNormalBlurEffect {
	return &NullableNormalBlurEffect{value: val, isSet: true}
}

func (v NullableNormalBlurEffect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNormalBlurEffect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
