/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
	"fmt"
)

// checks if the TriggerOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerOneOf{}

// TriggerOneOf struct for TriggerOneOf
type TriggerOneOf struct {
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _TriggerOneOf TriggerOneOf

// NewTriggerOneOf instantiates a new TriggerOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerOneOf(type_ string) *TriggerOneOf {
	this := TriggerOneOf{}
	this.Type = type_
	return &this
}

// NewTriggerOneOfWithDefaults instantiates a new TriggerOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerOneOfWithDefaults() *TriggerOneOf {
	this := TriggerOneOf{}
	return &this
}

// GetType returns the Type field value
func (o *TriggerOneOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TriggerOneOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TriggerOneOf) SetType(v string) {
	o.Type = v
}

func (o TriggerOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TriggerOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTriggerOneOf := _TriggerOneOf{}

	err = json.Unmarshal(data, &varTriggerOneOf)

	if err != nil {
		return err
	}

	*o = TriggerOneOf(varTriggerOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTriggerOneOf struct {
	value *TriggerOneOf
	isSet bool
}

func (v NullableTriggerOneOf) Get() *TriggerOneOf {
	return v.value
}

func (v *NullableTriggerOneOf) Set(val *TriggerOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerOneOf(val *TriggerOneOf) *NullableTriggerOneOf {
	return &NullableTriggerOneOf{value: val, isSet: true}
}

func (v NullableTriggerOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
