/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ComponentPropertyValue - Value of the property for this component instance.
type ComponentPropertyValue struct {
	Bool   *bool
	String *string
}

// boolAsComponentPropertyValue is a convenience function that returns bool wrapped in ComponentPropertyValue
func BoolAsComponentPropertyValue(v *bool) ComponentPropertyValue {
	return ComponentPropertyValue{
		Bool: v,
	}
}

// stringAsComponentPropertyValue is a convenience function that returns string wrapped in ComponentPropertyValue
func StringAsComponentPropertyValue(v *string) ComponentPropertyValue {
	return ComponentPropertyValue{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ComponentPropertyValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ComponentPropertyValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(ComponentPropertyValue): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(ComponentPropertyValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ComponentPropertyValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ComponentPropertyValue) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ComponentPropertyValue) GetActualInstanceValue() interface{} {
	if obj.Bool != nil {
		return *obj.Bool
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableComponentPropertyValue struct {
	value *ComponentPropertyValue
	isSet bool
}

func (v NullableComponentPropertyValue) Get() *ComponentPropertyValue {
	return v.value
}

func (v *NullableComponentPropertyValue) Set(val *ComponentPropertyValue) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentPropertyValue) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentPropertyValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentPropertyValue(val *ComponentPropertyValue) *NullableComponentPropertyValue {
	return &NullableComponentPropertyValue{value: val, isSet: true}
}

func (v NullableComponentPropertyValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentPropertyValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
