/*
Figma API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package figma

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TextureEffect type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextureEffect{}

// TextureEffect A texture effect
type TextureEffect struct {
	// The string literal 'TEXTURE' representing the effect's type. Always check the type before reading other properties.
	Type string `json:"type"`
	// Whether the texture effect is visible.
	Visible bool `json:"visible"`
	// The size of the texture effect
	NoiseSize float32 `json:"noiseSize"`
	// The radius of the texture effect
	Radius float32 `json:"radius"`
	// Whether the texture is clipped to the shape
	ClipToShape bool `json:"clipToShape"`
}

type _TextureEffect TextureEffect

// NewTextureEffect instantiates a new TextureEffect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextureEffect(type_ string, visible bool, noiseSize float32, radius float32, clipToShape bool) *TextureEffect {
	this := TextureEffect{}
	this.Type = type_
	this.Visible = visible
	this.NoiseSize = noiseSize
	this.Radius = radius
	this.ClipToShape = clipToShape
	return &this
}

// NewTextureEffectWithDefaults instantiates a new TextureEffect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextureEffectWithDefaults() *TextureEffect {
	this := TextureEffect{}
	return &this
}

// GetType returns the Type field value
func (o *TextureEffect) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TextureEffect) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TextureEffect) SetType(v string) {
	o.Type = v
}

// GetVisible returns the Visible field value
func (o *TextureEffect) GetVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value
// and a boolean to check if the value has been set.
func (o *TextureEffect) GetVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visible, true
}

// SetVisible sets field value
func (o *TextureEffect) SetVisible(v bool) {
	o.Visible = v
}

// GetNoiseSize returns the NoiseSize field value
func (o *TextureEffect) GetNoiseSize() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.NoiseSize
}

// GetNoiseSizeOk returns a tuple with the NoiseSize field value
// and a boolean to check if the value has been set.
func (o *TextureEffect) GetNoiseSizeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoiseSize, true
}

// SetNoiseSize sets field value
func (o *TextureEffect) SetNoiseSize(v float32) {
	o.NoiseSize = v
}

// GetRadius returns the Radius field value
func (o *TextureEffect) GetRadius() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Radius
}

// GetRadiusOk returns a tuple with the Radius field value
// and a boolean to check if the value has been set.
func (o *TextureEffect) GetRadiusOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Radius, true
}

// SetRadius sets field value
func (o *TextureEffect) SetRadius(v float32) {
	o.Radius = v
}

// GetClipToShape returns the ClipToShape field value
func (o *TextureEffect) GetClipToShape() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClipToShape
}

// GetClipToShapeOk returns a tuple with the ClipToShape field value
// and a boolean to check if the value has been set.
func (o *TextureEffect) GetClipToShapeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClipToShape, true
}

// SetClipToShape sets field value
func (o *TextureEffect) SetClipToShape(v bool) {
	o.ClipToShape = v
}

func (o TextureEffect) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextureEffect) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["visible"] = o.Visible
	toSerialize["noiseSize"] = o.NoiseSize
	toSerialize["radius"] = o.Radius
	toSerialize["clipToShape"] = o.ClipToShape
	return toSerialize, nil
}

func (o *TextureEffect) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"visible",
		"noiseSize",
		"radius",
		"clipToShape",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTextureEffect := _TextureEffect{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTextureEffect)

	if err != nil {
		return err
	}

	*o = TextureEffect(varTextureEffect)

	return err
}

type NullableTextureEffect struct {
	value *TextureEffect
	isSet bool
}

func (v NullableTextureEffect) Get() *TextureEffect {
	return v.value
}

func (v *NullableTextureEffect) Set(val *TextureEffect) {
	v.value = val
	v.isSet = true
}

func (v NullableTextureEffect) IsSet() bool {
	return v.isSet
}

func (v *NullableTextureEffect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextureEffect(val *TextureEffect) *NullableTextureEffect {
	return &NullableTextureEffect{value: val, isSet: true}
}

func (v NullableTextureEffect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextureEffect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
